export type FactLocale = { es: string; en: string; fr: string; pt: string }

export const CHARACTER_FUN_FACTS: Record<string, FactLocale> = {
  'spider-man': {
    es: 'El traje negro de Spider-Man que se convirtió en Venom fue diseñado originalmente por un fan de 22 años en una competición. Stan Lee lo eligió entre miles de propuestas y le pagó 220 dólares.',
    en: 'The black Spider-Man suit that became Venom was designed by a 22-year-old fan in a contest. Stan Lee picked it from thousands of entries and paid the fan $220.',
    fr: 'Le costume noir de Spider-Man qui est devenu Venom a été conçu par un fan de 22 ans lors d\'un concours. Stan Lee l\'a choisi parmi des milliers de propositions pour 220 dollars.',
    pt: 'O traje preto do Spider-Man que se tornou Venom foi criado por um fã de 22 anos num concurso. Stan Lee escolheu-o entre milhares de propostas e pagou ao fã 220 dólares.',
  },
  'iron-man': {
    es: 'Tony Stark inspiró a Elon Musk. El propio Musk lo reconoció públicamente y apareció haciendo un cameo en Iron Man 2. Robert Downey Jr. visitó los laboratorios de SpaceX para preparar el papel.',
    en: 'Tony Stark inspired Elon Musk — Musk even said so publicly and made a cameo in Iron Man 2. Robert Downey Jr. visited SpaceX labs to prepare for the role.',
    fr: 'Tony Stark a inspiré Elon Musk, qui l\'a reconnu publiquement et est apparu en caméo dans Iron Man 2. Robert Downey Jr. a visité les laboratoires de SpaceX pour préparer le rôle.',
    pt: 'Tony Stark inspirou Elon Musk, que o admitiu publicamente e fez uma aparição em Iron Man 2. Robert Downey Jr. visitou os laboratórios da SpaceX para se preparar para o papel.',
  },
  'captain-america': {
    es: 'El escudo del Capitán América apareció por primera vez en 1941... y en los primeros cómics se rompió varias veces. La versión indestructible de vibranio llegó décadas después.',
    en: 'Captain America\'s shield first appeared in 1941 — and in early comics it actually broke several times. The indestructible vibranium version came decades later.',
    fr: 'Le bouclier de Captain America est apparu pour la première fois en 1941 et s\'est cassé plusieurs fois dans les premières bandes dessinées. La version indestructible en vibranium est arrivée des décennies plus tard.',
    pt: 'O escudo do Capitão América apareceu pela primeira vez em 1941 e nos primeiros quadrinhos chegou a quebrar várias vezes. A versão indestrutível de vibranium surgiu décadas depois.',
  },
  'hulk': {
    es: 'En los primeros cómics de 1962, Hulk era GRIS, no verde. Lo cambiaron a verde porque el tinte gris era inconsistente en imprenta y cada número salía de un tono diferente.',
    en: 'In the original 1962 comics, the Hulk was GREY, not green. They changed it because the grey ink was inconsistent and each issue came out a slightly different shade.',
    fr: 'Dans les premières bandes dessinées de 1962, Hulk était GRIS, pas vert. Ils l\'ont changé en vert parce que l\'encre grise était inconsistante et chaque numéro sortait d\'une teinte différente.',
    pt: 'Nos primeiros quadrinhos de 1962, o Hulk era CINZENTO, não verde. Mudaram para verde porque a tinta cinzenta era inconsistente e cada número saía de uma tonalidade diferente.',
  },
  'thor': {
    es: 'El martillo Mjolnir en nórdico antiguo significa "el triturador". Los vikingos reales llevaban réplicas en miniatura como amuletos de buena suerte, como quien lleva una cruz.',
    en: 'Mjolnir means "the crusher" in Old Norse. Real Vikings wore miniature replicas as good luck charms — basically the Viking equivalent of wearing a cross.',
    fr: 'Mjolnir signifie "le broyeur" en vieux norrois. Les vrais Vikings portaient des répliques miniatures comme porte-bonheur, l\'équivalent viking d\'une croix.',
    pt: 'Mjolnir significa "o triturador" em nórdico antigo. Os vikings reais usavam réplicas em miniatura como amuletos de boa sorte, o equivalente viking de uma cruz.',
  },
  'black-widow': {
    es: 'Natasha Romanoff tiene más de 70 años en los cómics gracias al suero de longevidad del KGB, pero luce como si tuviera 30. Su primera aparición fue en 1964 como villana, no como heroína.',
    en: 'In the comics, Natasha Romanoff is over 70 years old thanks to a KGB longevity serum — she just looks 30. She actually debuted in 1964 as a villain, not a hero.',
    fr: 'Dans les comics, Natasha Romanoff a plus de 70 ans grâce à un sérum de longévité du KGB, mais elle paraît 30 ans. Elle a fait ses débuts en 1964 comme vilaine, pas comme héroïne.',
    pt: 'Nos quadrinhos, Natasha Romanoff tem mais de 70 anos graças a um soro de longevidade do KGB, mas aparenta ter 30. A sua primeira aparição foi em 1964 como vilã, não como heroína.',
  },
  'venom': {
    es: 'El simbionte Venom está tan fusionado con Eddie Brock que ya no puede sobrevivir solo. Su nombre original en los primeros guiones era "el Otro"... y casi le llaman "Bodysuit".',
    en: 'The Venom symbiote is so merged with Eddie Brock it can\'t survive alone anymore. Early scripts called it "the Other" — and one writer wanted to call it "Bodysuit".',
    fr: 'Le symbiote Venom est tellement fusionné avec Eddie Brock qu\'il ne peut plus survivre seul. Les premiers scripts l\'appelaient "l\'Autre" — et un scénariste voulait l\'appeler "Bodysuit".',
    pt: 'O simbionte Venom está tão fundido com Eddie Brock que já não consegue sobreviver sozinho. Os primeiros guiões chamavam-lhe "o Outro" — e um escritor queria chamá-lo de "Bodysuit".',
  },
  'deadpool': {
    es: 'Deadpool es el único personaje de Marvel que sabe que vive dentro de un cómic. A esto se le llama "romper la cuarta pared". Y lo usa para hacer chistes sobre los propios guionistas.',
    en: 'Deadpool is the only Marvel character who knows he lives inside a comic book. It\'s called "breaking the fourth wall" — and he uses it to make jokes about his own writers.',
    fr: 'Deadpool est le seul personnage Marvel qui sait qu\'il vit dans une bande dessinée. On appelle ça "briser le quatrième mur" — et il l\'utilise pour faire des blagues sur ses propres scénaristes.',
    pt: 'Deadpool é o único personagem da Marvel que sabe que vive dentro de um quadrinho. Chama-se "quebrar a quarta parede" — e ele usa isso para fazer piadas sobre os seus próprios roteiristas.',
  },
  'wolverine': {
    es: 'Las garras de adamantio de Wolverine pesan aproximadamente 10 kg cada una. Sin su factor de curación, los huesos se habrían destruido hace mucho. Básicamente tiene las muñecas más fuertes del universo Marvel.',
    en: 'Wolverine\'s adamantium claws weigh around 10 kg each. Without his healing factor, his wrists would have shattered long ago. He basically has the strongest wrists in the Marvel universe.',
    fr: 'Les griffes en adamantium de Wolverine pèsent environ 10 kg chacune. Sans son facteur de guérison, ses poignets se seraient brisés depuis longtemps. Il a littéralement les poignets les plus solides de l\'univers Marvel.',
    pt: 'As garras de adamantium do Wolverine pesam cerca de 10 kg cada uma. Sem o seu fator de cura, os pulsos já teriam destruído há muito tempo. Ele tem basicamente os pulsos mais fortes do universo Marvel.',
  },
  'thanos': {
    es: 'El nombre Thanos viene de Thanatos, el dios griego de la muerte. En los cómics, su obsesión con el exterminio no es filosófica: está enamorado de la Muerte personificada y quiere impresionarla.',
    en: 'Thanos\'s name comes from Thanatos, the Greek god of death. In the comics, his obsession with wiping out life isn\'t philosophical — he\'s literally in love with the personification of Death and wants to impress her.',
    fr: 'Le nom Thanos vient de Thanatos, le dieu grec de la mort. Dans les comics, son obsession pour l\'extermination n\'est pas philosophique : il est littéralement amoureux de la personnification de la Mort.',
    pt: 'O nome Thanos vem de Thanatos, o deus grego da morte. Nos quadrinhos, a sua obsessão com o extermínio não é filosófica: ele está literalmente apaixonado pela personificação da Morte.',
  },
  'doctor-strange': {
    es: 'Benedict Cumberbatch reconoció que no entendió nada del guión cuando lo leyó por primera vez. Tuvo que ver vídeos de YouTube sobre budismo y magia para prepararse. Al menos fue honesto.',
    en: 'Benedict Cumberbatch admitted he didn\'t understand the script at all when he first read it. He had to watch YouTube videos about Buddhism and magic to prepare. At least he was honest about it.',
    fr: 'Benedict Cumberbatch a admis ne pas avoir compris le scénario lors de sa première lecture. Il a dû regarder des vidéos YouTube sur le bouddhisme et la magie pour se préparer.',
    pt: 'Benedict Cumberbatch admitiu que não entendeu nada do guião quando o leu pela primeira vez. Teve de ver vídeos no YouTube sobre budismo e magia para se preparar.',
  },
  'black-panther': {
    es: 'Wakanda fue el primer estado africano ficticio representado como tecnológicamente superior al mundo occidental. Apareció en los cómics en 1966, un año antes de que Martin Luther King recibiera el Nobel.',
    en: 'Wakanda was the first fictional African nation portrayed as technologically superior to the Western world — and it appeared in comics in 1966, a year before MLK received the Nobel Prize.',
    fr: 'Wakanda a été la première nation africaine fictive représentée comme technologiquement supérieure au monde occidental. Elle est apparue dans les comics en 1966, un an avant que MLK reçoive le Nobel.',
    pt: 'Wakanda foi a primeira nação africana fictícia retratada como tecnologicamente superior ao mundo ocidental. Apareceu nos quadrinhos em 1966, um ano antes de MLK receber o Nobel.',
  },
  'wanda': {
    es: 'Wanda puede reescribir la realidad entera con un pensamiento. En los cómics borró a casi todos los mutantes con solo tres palabras: "No more mutants". Técnicamente es el ser más peligroso del UCM.',
    en: 'Wanda can rewrite all of reality with a single thought. In the comics she depowered almost every mutant with just three words: "No more mutants." She\'s technically the most dangerous being in the MCU.',
    fr: 'Wanda peut réécrire toute la réalité d\'une seule pensée. Dans les comics, elle a dépuissé presque tous les mutants avec trois mots : "No more mutants." Elle est techniquement l\'être le plus dangereux de l\'UCM.',
    pt: 'Wanda pode reescrever toda a realidade com um único pensamento. Nos quadrinhos, despotencializou quase todos os mutantes com apenas três palavras: "No more mutants." É tecnicamente o ser mais perigoso do UCM.',
  },
  'loki': {
    es: 'Tom Hiddleston aprendió el lenguaje corporal de un jaguar para interpretar a Loki: movimientos fluidos, silenciosos e imprevisibles. Su director le dijo que fuera "el gato más peligroso de la sala".',
    en: 'Tom Hiddleston studied jaguar body language to play Loki — fluid, silent, unpredictable movements. His director told him to be "the most dangerous cat in the room."',
    fr: 'Tom Hiddleston a étudié le langage corporel du jaguar pour jouer Loki : mouvements fluides, silencieux, imprévisibles. Son réalisateur lui a dit d\'être "le chat le plus dangereux de la pièce".',
    pt: 'Tom Hiddleston estudou a linguagem corporal de um jaguar para interpretar Loki: movimentos fluidos, silenciosos e imprevisíveis. O seu realizador disse-lhe para ser "o gato mais perigoso da sala".',
  },
  'batman': {
    es: 'A pesar de ser multimillonario, Batman no tiene superpoderes. Su arma más poderosa es el miedo: toda su estrategia se basa en aterrorizar a los criminales. Básicamente es el mejor actor de terror del mundo.',
    en: 'Despite being a billionaire, Batman has no superpowers. His most powerful weapon is fear — his entire strategy relies on terrifying criminals. He\'s basically the world\'s greatest horror actor.',
    fr: 'Malgré sa fortune, Batman n\'a aucun superpouvoir. Son arme la plus puissante est la peur : toute sa stratégie repose sur la terreur des criminels. Il est fondamentalement le meilleur acteur d\'horreur du monde.',
    pt: 'Apesar de ser bilionário, Batman não tem superpoderes. A sua arma mais poderosa é o medo: toda a sua estratégia baseia-se em aterrorizar criminosos. É basicamente o melhor ator de terror do mundo.',
  },
  'superman': {
    es: 'El cómic original de Superman de 1938 se vendía por 10 céntimos. Una copia en buen estado puede valer hoy más de 3 millones de dólares. El mayor error de aquel que lo tiró.',
    en: 'The original 1938 Superman comic sold for 10 cents. A copy in good condition can be worth over $3 million today. The greatest mistake of whoever threw theirs away.',
    fr: 'Le comic original Superman de 1938 se vendait 10 centimes. Une copie en bon état peut valoir plus de 3 millions de dollars aujourd\'hui. La plus grande erreur de ceux qui l\'ont jeté.',
    pt: 'O quadrinho original do Superman de 1938 vendia-se por 10 cêntimos. Uma cópia em bom estado pode valer mais de 3 milhões de dólares hoje. O maior erro de quem o atirou fora.',
  },
  'joker': {
    es: 'El Joker no tiene nombre real en los cómics. Ni DC sabe quién es. Ha dado tantas versiones de su propio origen que ninguna puede considerarse canónica. Es literalmente el villano más misterioso de la historia.',
    en: 'The Joker has no real name in the comics — even DC doesn\'t know who he is. He\'s given so many versions of his own origin that none can be considered canon. He\'s literally the most mysterious villain in history.',
    fr: 'Le Joker n\'a pas de vrai nom dans les comics — même DC ne sait pas qui il est. Il a donné tellement de versions de sa propre origine qu\'aucune ne peut être considérée comme canonique.',
    pt: 'O Joker não tem nome real nos quadrinhos — nem a DC sabe quem ele é. Deu tantas versões da sua própria origem que nenhuma pode ser considerada canónica.',
  },
  'wonder-woman': {
    es: 'Wonder Woman fue creada por William Moulton Marston, el mismo psicólogo que inventó el detector de mentiras. Su Lazo de la Verdad no es casualidad: era su obsesión con la verdad llevada al cómic.',
    en: 'Wonder Woman was created by William Moulton Marston — the same psychologist who invented the lie detector. Her Lasso of Truth wasn\'t a coincidence; it was his obsession with truth made into a comic.',
    fr: 'Wonder Woman a été créée par William Moulton Marston, le même psychologue qui a inventé le détecteur de mensonges. Son Lasso de Vérité n\'est pas un hasard : c\'était son obsession pour la vérité transposée en comics.',
    pt: 'Wonder Woman foi criada por William Moulton Marston, o mesmo psicólogo que inventou o detector de mentiras. O Laço da Verdade não foi coincidência: era a sua obsessão com a verdade transformada em quadrinho.',
  },
  'flash': {
    es: 'Barry Allen corre tan rápido que puede viajar en el tiempo. Pero cuando lo intentó para salvar a su madre, creó sin querer una realidad alternativa donde Batman era... Thomas Wayne. Al padre de Bruce. Oops.',
    en: 'Barry Allen runs so fast he can travel through time. But when he tried to save his mom, he accidentally created an alternate reality where Batman was... Thomas Wayne. Bruce\'s dad. Oops.',
    fr: 'Barry Allen court si vite qu\'il peut voyager dans le temps. Mais quand il a essayé de sauver sa mère, il a accidentellement créé une réalité alternative où Batman était... Thomas Wayne. Le père de Bruce. Aïe.',
    pt: 'Barry Allen corre tão rápido que consegue viajar no tempo. Mas quando tentou salvar a sua mãe, criou acidentalmente uma realidade alternativa onde o Batman era... Thomas Wayne. O pai de Bruce. Ups.',
  },
  'aquaman': {
    es: 'El 71% de la superficie del planeta Tierra es agua. Aquaman controla el 71% del planeta. Que digan lo que quieran sobre él, los números no mienten.',
    en: '71% of the Earth\'s surface is water. Aquaman controls 71% of the planet. Say what you want about him — the numbers don\'t lie.',
    fr: '71% de la surface de la Terre est de l\'eau. Aquaman contrôle 71% de la planète. Dites ce que vous voulez, les chiffres ne mentent pas.',
    pt: '71% da superfície da Terra é água. Aquaman controla 71% do planeta. Digam o que quiserem sobre ele — os números não mentem.',
  },
  'naruto': {
    es: 'El nombre "Naruto" viene de los remolinos de pasta llamados narutomaki que flotan en el ramen. Y sí, su comida favorita es el ramen de cerdo con extra de narutomaki. El autor es muy consistente.',
    en: '"Naruto" is named after narutomaki — the spiral fish cake that floats in ramen. And yes, his favorite food is pork ramen with extra narutomaki. The author is very consistent.',
    fr: '"Naruto" tient son nom du narutomaki — le gâteau de poisson en spirale qui flotte dans le ramen. Et oui, son plat préféré est le ramen au porc avec du narutomaki supplémentaire.',
    pt: '"Naruto" tem o nome do narutomaki — o bolo de peixe em espiral que flutua no ramen. E sim, a sua comida favorita é ramen de porco com narutomaki extra. O autor é muito consistente.',
  },
  'goku': {
    es: 'El nombre saiyano de Goku, "Kakarotto", está inspirado en "carrot" (zanahoria) en inglés. En el universo DBZ, todos los saiyanos llevan nombre de verduras: Vegeta, Raditz, Kakarotto...',
    en: 'Goku\'s Saiyan name "Kakarot" is inspired by "carrot." In the DBZ universe, all Saiyans are named after vegetables: Vegeta, Raditz, Kakarot — they\'re basically a race of cosmic veggie lovers.',
    fr: 'Le nom saiyen de Goku, "Kakarot", s\'inspire de "carrot" (carotte) en anglais. Dans l\'univers DBZ, tous les Saiyens portent des noms de légumes : Vegeta, Raditz, Kakarot...',
    pt: 'O nome saiyano de Goku, "Kakarot", é inspirado em "carrot" (cenoura) em inglês. No universo DBZ, todos os Saiyanos têm nomes de vegetais: Vegeta, Raditz, Kakarot...',
  },
  'sasuke': {
    es: 'Sasuke se llama igual que el legendario ninja histórico japonés Sarutobi Sasuke. Es básicamente el Spider-Man del Japón feudal, solo que con más trauma familiar y pelo más elaborado.',
    en: 'Sasuke is named after legendary historical Japanese ninja Sarutobi Sasuke — basically the Spider-Man of feudal Japan, except with more family trauma and fancier hair.',
    fr: 'Sasuke porte le nom du légendaire ninja historique japonais Sarutobi Sasuke — le Spider-Man du Japon féodal, mais avec plus de traumatisme familial et une coiffure plus élaborée.',
    pt: 'Sasuke tem o nome do lendário ninja histórico japonês Sarutobi Sasuke — basicamente o Spider-Man do Japão feudal, mas com mais trauma familiar e cabelo mais elaborado.',
  },
  'luffy': {
    es: 'La cicatriz de Luffy bajo el ojo izquierdo se la hizo él mismo con un cuchillo a los 7 años para demostrarle a Shanks que era valiente. Shanks lloró. Los lectores también.',
    en: 'The scar under Luffy\'s left eye? He gave it to himself with a knife at age 7 to prove to Shanks he was brave. Shanks cried. So did the readers.',
    fr: 'La cicatrice sous l\'œil gauche de Luffy ? Il se l\'est faite lui-même avec un couteau à 7 ans pour prouver à Shanks qu\'il était courageux. Shanks a pleuré. Les lecteurs aussi.',
    pt: 'A cicatriz debaixo do olho esquerdo de Luffy? Ele deu a si próprio com uma faca aos 7 anos para provar a Shanks que era corajoso. Shanks chorou. Os leitores também.',
  },
  'zoro': {
    es: 'Zoro siempre se pierde, y Oda nunca lo explica. Es el segundo personaje más poderoso de la tripulación... y no puede encontrar la puerta de su propia habitación. El misterio más grande de One Piece.',
    en: 'Zoro always gets lost, and Oda never explains it. He\'s the second strongest crew member — and he can\'t find the door to his own room. The greatest unsolved mystery of One Piece.',
    fr: 'Zoro se perd toujours, et Oda ne l\'explique jamais. C\'est le deuxième membre le plus fort de l\'équipage — et il ne peut pas trouver la porte de sa propre chambre.',
    pt: 'Zoro perde-se sempre, e Oda nunca explica porquê. É o segundo membro mais forte da tripulação — e não consegue encontrar a porta do seu próprio quarto. O maior mistério de One Piece.',
  },
  'tanjiro': {
    es: 'El pendiente de Tanjiro tiene forma de sol y no es decorativo: es el símbolo de la Danza del Dios del Sol, la única técnica capaz de matar a Muzan. Literalmente lleva la solución al cuello desde el principio.',
    en: 'Tanjiro\'s earring is shaped like a sun and it\'s not decorative — it\'s the symbol of the Sun Breathing technique, the only move that can kill Muzan. He\'s been wearing the answer around his neck all along.',
    fr: 'La boucle d\'oreille de Tanjiro a la forme d\'un soleil et n\'est pas décorative : c\'est le symbole de la Danse du Dieu Soleil, la seule technique capable de tuer Muzan. Il porte littéralement la solution autour du cou depuis le début.',
    pt: 'O brinco de Tanjiro tem forma de sol e não é decorativo: é o símbolo da Dança do Deus do Sol, a única técnica capaz de matar Muzan. Literalmente carregou a solução no pescoço desde o início.',
  },
  'deku': {
    es: 'Izuku Midoriya llenó más de 13 cuadernos de análisis de superhéroes antes de conseguir su propio poder. Los llama "Hero Analysis for the Future". Un hombre planificador en un mundo de musculosos impulsivos.',
    en: 'Izuku Midoriya filled over 13 notebooks analyzing heroes before he ever got a power. He calls them "Hero Analysis for the Future." A planner in a world full of impulsive muscle-heads.',
    fr: 'Izuku Midoriya a rempli plus de 13 cahiers d\'analyse de superhéros avant d\'avoir son propre pouvoir. Il les appelle "Hero Analysis for the Future". Un planificateur dans un monde de têtes brûlées musclées.',
    pt: 'Izuku Midoriya preencheu mais de 13 cadernos de análise de super-heróis antes de ter o seu próprio poder. Chama-lhes "Hero Analysis for the Future". Um planeador num mundo de impulsivos musculados.',
  },
  'gojo': {
    es: 'Gojo usa la venda en los ojos porque sus pupilas del Infinito le permiten ver a nivel atómico, lo que marea a cualquiera que lo mire. La quita cuando quiere que alguien realmente sufra. Dramático con mucha razón.',
    en: 'Gojo wears his blindfold because his Infinity Eyes let him see at an atomic level — which makes anyone he looks at dizzy. He removes it when he wants someone to really suffer. Maximum drama, maximum reason.',
    fr: 'Gojo porte son bandeau parce que ses Yeux Infinis lui permettent de voir à l\'échelle atomique, ce qui rend tout le monde qu\'il regarde étourdi. Il l\'enlève quand il veut que quelqu\'un souffre vraiment.',
    pt: 'Gojo usa a venda porque os seus Olhos do Infinito permitem-lhe ver a nível atómico, o que enjoa qualquer pessoa que ele olhe. Tira-a quando quer que alguém realmente sofra. Drama máximo.',
  },
  'levi-ackerman': {
    es: 'Levi mide 1,60 m, igual que Naruto. Pero mientras Naruto lo menciona constantemente y lo sufre, Levi nunca habló de su altura. Porque Levi no necesita hablar de esas cosas.',
    en: 'Levi is 1.60m tall — same as Naruto. But while Naruto constantly mentions and suffers about his height, Levi never talks about it. Because Levi doesn\'t need to talk about those things.',
    fr: 'Levi mesure 1,60m, comme Naruto. Mais alors que Naruto le mentionne constamment et en souffre, Levi n\'en parle jamais. Parce que Levi n\'a pas besoin de parler de ces choses.',
    pt: 'Levi mede 1,60m, igual ao Naruto. Mas enquanto Naruto menciona constantemente e sofre com a sua altura, Levi nunca fala sobre isso. Porque Levi não precisa de falar dessas coisas.',
  },
  'eren-yeager': {
    es: 'El nombre Eren significa "hombre sabio" en turco. Y efectivamente, Eren alcanzó el conocimiento que nadie más quería tener. El autor de AoT es turco y el nombre es absolutamente intencional.',
    en: 'Eren means "wise man" or "he who achieves" in Turkish. And indeed, Eren reached a knowledge no one else wanted to have. The AoT author is of Turkish heritage — the name was absolutely intentional.',
    fr: 'Eren signifie "homme sage" ou "celui qui atteint" en turc. Et en effet, Eren a atteint une connaissance que personne d\'autre ne voulait avoir. L\'auteur d\'AoT est d\'origine turque — le nom était absolument intentionnel.',
    pt: 'Eren significa "homem sábio" ou "aquele que alcança" em turco. E de facto, Eren alcançou um conhecimento que mais ninguém queria ter. O autor de AoT tem herança turca — o nome foi absolutamente intencional.',
  },
  'saitama': {
    es: 'Saitama perdió el pelo por entrenar 100 flexiones, 100 abdominales, 100 sentadillas y 10 km al día durante 3 años. Según él, también perdió sus emociones. El precio del poder absoluto: la calvicie.',
    en: 'Saitama went bald from training 100 push-ups, 100 sit-ups, 100 squats, and 10km a day for 3 years. According to him, he also lost his emotions. The price of absolute power: baldness.',
    fr: 'Saitama est devenu chauve en s\'entraînant avec 100 pompes, 100 abdominaux, 100 squats et 10 km par jour pendant 3 ans. Selon lui, il a aussi perdu ses émotions. Le prix du pouvoir absolu : la calvitie.',
    pt: 'Saitama ficou careca de treinar 100 flexões, 100 abdominais, 100 agachamentos e 10 km por dia durante 3 anos. Segundo ele, também perdeu as suas emoções. O preço do poder absoluto: a calvície.',
  },
  'itachi': {
    es: 'Itachi tomó una de las decisiones más difíciles de toda la historia del anime a los 13 años. La mayoría de adultos no podrían. Y encima enfermó para no hacerlo demasiado fácil. Naruto era injusto con Itachi.',
    en: 'Itachi made one of the hardest decisions in all of anime at age 13. Most adults couldn\'t. And then he got sick to make sure it wouldn\'t be too easy on himself. Naruto\'s world was unfair to Itachi.',
    fr: 'Itachi a pris l\'une des décisions les plus difficiles de toute l\'histoire de l\'anime à 13 ans. La plupart des adultes n\'en seraient pas capables. Et en plus, il est tombé malade pour ne pas le rendre trop facile.',
    pt: 'Itachi tomou uma das decisões mais difíceis de toda a história do anime aos 13 anos. A maioria dos adultos não conseguiria. E por cima ainda ficou doente para não tornar as coisas demasiado fáceis.',
  },
  'vegeta': {
    es: 'Vegeta es el príncipe de todos los saiyanos. Literalmente. El único problema es que su planeta explotó, así que reina sobre... 5 personas que quedan vivas. El trono más solitario del universo.',
    en: 'Vegeta is the prince of all Saiyans. Literally. The only problem is his planet exploded, so he rules over... about 5 surviving Saiyans. The loneliest throne in the universe.',
    fr: 'Vegeta est le prince de tous les Saiyens. Littéralement. Le seul problème est que sa planète a explosé, donc il règne sur... environ 5 Saiyens survivants. Le trône le plus solitaire de l\'univers.',
    pt: 'Vegeta é o príncipe de todos os Saiyanos. Literalmente. O único problema é que o seu planeta explodiu, por isso reina sobre... 5 Saiyanos sobreviventes. O trono mais solitário do universo.',
  },
  'master-chief': {
    es: 'El nombre real de Master Chief es John-117. El 117 es su número de Spartan. Lleva el casco puesto en casi todos los juegos porque los desarrolladores de Bungie... nunca decidieron cómo renderizar su cara.',
    en: 'Master Chief\'s real name is John-117. The number is his Spartan designation. He keeps his helmet on in almost every game because the Bungie developers... never agreed on what his face should look like.',
    fr: 'Le vrai nom de Master Chief est John-117. Le chiffre est son numéro de Spartan. Il garde son casque dans presque tous les jeux parce que les développeurs de Bungie... n\'ont jamais pu s\'accorder sur ce à quoi son visage devrait ressembler.',
    pt: 'O nome real do Master Chief é John-117. O número é a sua designação Spartan. Usa o capacete em quase todos os jogos porque os desenvolvedores da Bungie... nunca decidiram como renderizar a sua cara.',
  },
  'steve-minecraft': {
    es: 'Steve fue el skin por defecto de Minecraft durante 9 años hasta 2014. Nadie sabe su apellido. Notch dijo en Twitter que era "Steve?", con interrogación, lo que no aclara absolutamente nada.',
    en: 'Steve was Minecraft\'s default skin for 9 years until 2014. Nobody knows his last name. Notch once tweeted it was "Steve?" — with a question mark — which clarifies absolutely nothing.',
    fr: 'Steve était le skin par défaut de Minecraft pendant 9 ans jusqu\'en 2014. Personne ne connaît son nom de famille. Notch a tweeté que c\'était "Steve?" — avec un point d\'interrogation — ce qui ne clarifie absolument rien.',
    pt: 'Steve foi o skin padrão do Minecraft durante 9 anos até 2014. Ninguém sabe o seu apelido. Notch tweetou que era "Steve?" — com ponto de interrogação — o que não esclarece absolutamente nada.',
  },
  'alex-minecraft': {
    es: 'Alex fue añadida en 2014 como alternativa a Steve para "diversidad". Es oficialmente más ágil que Steve, tiene brazos más delgados y una personalidad completamente no definida. La perfecta lienzo en blanco.',
    en: 'Alex was added in 2014 as an alternative to Steve for "diversity." She\'s officially more agile than Steve, has slimmer arms, and a completely undefined personality. The perfect blank canvas.',
    fr: 'Alex a été ajoutée en 2014 comme alternative à Steve pour la "diversité". Elle est officiellement plus agile que Steve, a des bras plus fins et une personnalité complètement indéfinie.',
    pt: 'Alex foi adicionada em 2014 como alternativa ao Steve para "diversidade". É oficialmente mais ágil que Steve, tem braços mais finos e uma personalidade completamente indefinida. A tela em branco perfeita.',
  },
  'mario': {
    es: 'Mario se llamaba originalmente "Jumpman" y era carpintero, no fontanero. La razión del cambio de profesión: en Donkey Kong no había tuberías. En Super Mario Bros. las había. Decisión de arte, no de guión.',
    en: 'Mario was originally called "Jumpman" and was a carpenter, not a plumber. The profession change happened because Donkey Kong had no pipes. Super Mario Bros. had plenty. An art decision, not a story one.',
    fr: 'Mario s\'appelait à l\'origine "Jumpman" et était charpentier, pas plombier. Le changement de profession est survenu parce que Donkey Kong n\'avait pas de tuyaux. Super Mario Bros. en avait beaucoup.',
    pt: 'Mario chamava-se originalmente "Jumpman" e era carpinteiro, não canalizador. A mudança de profissão aconteceu porque Donkey Kong não tinha canos. Super Mario Bros. tinha muitos.',
  },
  'luigi': {
    es: 'Luigi es técnicamente mejor saltador que Mario: en los juegos donde aparece, su salto es más alto y sus pies tienen menos fricción. Solo que nadie lo elige porque lleva el número 2 en el nombre.',
    en: 'Luigi is technically a better jumper than Mario — in games where he appears, his jump is higher and his feet have less friction. But nobody picks him because he has the number 2 in his name.',
    fr: 'Luigi est techniquement un meilleur sauteur que Mario : dans les jeux où il apparaît, son saut est plus haut et ses pieds ont moins de friction. Mais personne ne le choisit car il a le numéro 2 dans son nom.',
    pt: 'Luigi é tecnicamente um salto melhor que Mario — nos jogos onde aparece, o seu salto é mais alto e os seus pés têm menos atrito. Mas ninguém o escolhe porque tem o número 2 no nome.',
  },
  'link-zelda': {
    es: 'Link es zurdo en la mayoría de los juegos originales. En Skyward Sword para Wii lo cambiaron a diestro porque los controles de movimiento estaban diseñados para diestros. Los fans de Zelda todavía no lo han perdonado.',
    en: 'Link is left-handed in most original games. In Skyward Sword on Wii they made him right-handed because the motion controls were designed for right-handers. Zelda fans still haven\'t forgiven this.',
    fr: 'Link est gaucher dans la plupart des jeux originaux. Dans Skyward Sword sur Wii, ils l\'ont rendu droitier parce que les contrôles de mouvement étaient conçus pour les droitiers. Les fans de Zelda ne l\'ont toujours pas pardonné.',
    pt: 'Link é canhoto na maioria dos jogos originais. Em Skyward Sword na Wii tornaram-no destro porque os controlos de movimento foram concebidos para destros. Os fãs de Zelda ainda não perdoaram.',
  },
  'master-sword-link': {
    es: 'En Tears of the Kingdom, Link puede unir literalmente cualquier cosa a cualquier otra cosa. Los jugadores han construido desde helicópteros hasta locomotoras de vapor. Nintendo creó un motor físico y los jugadores lo convirtieron en arte.',
    en: 'In Tears of the Kingdom, Link can attach literally anything to anything else. Players have built helicopters, steam engines, and working roller coasters. Nintendo made a physics engine; players turned it into art.',
    fr: 'Dans Tears of the Kingdom, Link peut attacher littéralement n\'importe quoi à n\'importe quoi d\'autre. Les joueurs ont construit des hélicoptères, des locomotives à vapeur et des montagnes russes fonctionnelles.',
    pt: 'Em Tears of the Kingdom, Link pode ligar literalmente qualquer coisa a qualquer outra coisa. Os jogadores construíram helicópteros, locomotivas a vapor e montanhas-russas funcionais.',
  },
  'pikachu': {
    es: 'Pikachu fue diseñado inspirándose en ardillas japonesas (Momonga) que tienen mejillas infladas. El nombre viene de "pikapika" (destello eléctrico en japonés) y "chu", el sonido de un ratón.',
    en: 'Pikachu was designed based on Japanese dwarf flying squirrels (Momonga) with puffy cheeks. The name comes from "pikapika" (electric flash in Japanese) and "chu," the sound a mouse makes.',
    fr: 'Pikachu a été conçu en s\'inspirant des écureuils volants nains japonais (Momonga) aux joues gonflées. Le nom vient de "pikapika" (éclair électrique en japonais) et "chu", le son d\'une souris.',
    pt: 'Pikachu foi criado inspirando-se nos esquilos voadores japoneses (Momonga) com bochechas inchadas. O nome vem de "pikapika" (relâmpago elétrico em japonês) e "chu", o som de um rato.',
  },
  'charizard': {
    es: 'Charizard no es tipo Dragón en la primera generación. Es Fuego/Volador. Desde la 6ª generación tiene una Mega Evolución que SÍ es tipo Dragón... porque los fans se quejaron durante 15 años y Game Freak los escuchó.',
    en: 'Charizard is NOT Dragon type in Gen 1 — it\'s Fire/Flying. Starting from Gen 6 its Mega Evolution IS Dragon type... because fans complained for 15 years and Game Freak finally listened.',
    fr: 'Charizard n\'est PAS de type Dragon en génération 1 — c\'est Feu/Vol. À partir de la Gen 6, sa Méga Évolution EST de type Dragon... parce que les fans se sont plaints pendant 15 ans.',
    pt: 'Charizard NÃO é do tipo Dragão na 1ª geração — é Fogo/Voador. A partir da 6ª geração a sua Mega Evolução É do tipo Dragão... porque os fãs reclamaram durante 15 anos e a Game Freak ouviu.',
  },
  'sonic': {
    es: 'Sonic tiene un apellido: The Hedgehog. Pero según una guía oficial de 1993, su nombre completo no canónico era "Olgilvie Maurice Hedgehog". Sega lo borró de la existencia tan rápido como Sonic corre.',
    en: 'Sonic\'s full last name is "The Hedgehog." But according to a 1993 official guide, his unofficial full name was "Olgilvie Maurice Hedgehog." Sega erased it as fast as Sonic runs.',
    fr: 'Le nom complet de Sonic est "The Hedgehog". Mais selon un guide officiel de 1993, son vrai prénom non canonique était "Olgilvie Maurice Hedgehog". Sega l\'a effacé aussi vite que Sonic court.',
    pt: 'O sobrenome completo do Sonic é "The Hedgehog". Mas segundo um guia oficial de 1993, o seu nome completo não canónico era "Olgilvie Maurice Hedgehog". A Sega apagou-o tão rápido quanto Sonic corre.',
  },
  'kratos': {
    es: 'Kratos en griego antiguo significa "fuerza" o "poder". Su piel blanca no es su color natural: es la ceniza de su familia muerta, que se adhirió a él como maldición por lo que hizo. Cada batalla la lleva encima.',
    en: 'Kratos means "strength" or "power" in Ancient Greek. His white skin isn\'t natural — it\'s the ashes of his dead family, cursed to stick to him forever for what he did. He carries every battle on his skin.',
    fr: 'Kratos signifie "force" ou "pouvoir" en grec ancien. Sa peau blanche n\'est pas naturelle : ce sont les cendres de sa famille morte, maudites pour coller à lui pour toujours. Il porte chaque bataille sur sa peau.',
    pt: 'Kratos significa "força" ou "poder" em grego antigo. A sua pele branca não é natural: são as cinzas da sua família morta, malditas para se colarem a ele para sempre pelo que fez.',
  },
  'geralt': {
    es: 'Henry Cavill prepara sus propias comidas, construye sus propios ordenadores y leyó todos los libros de The Witcher antes de la audición. Es básicamente Geralt en la vida real, pero sin las cicatrices.',
    en: 'Henry Cavill cooks his own meals, builds his own PCs, and read every Witcher book before auditioning. He\'s basically Geralt in real life — just without the scars.',
    fr: 'Henry Cavill prépare ses propres repas, construit ses propres PC et a lu tous les livres de The Witcher avant l\'audition. C\'est essentiellement Geralt dans la vraie vie, sans les cicatrices.',
    pt: 'Henry Cavill prepara as suas próprias refeições, constrói os seus próprios PCs e leu todos os livros de The Witcher antes da audição. É basicamente Geralt na vida real, mas sem as cicatrizes.',
  },
  'jinx-arcane': {
    es: 'Jinx se llama en realidad Powder. Su transformación psicológica en Jinx es lo que le da nombre. La serie Arcane tardó 6 años en producirse y costó más que muchas películas de Hollywood.',
    en: 'Jinx\'s real name is Powder. Her psychological transformation into Jinx is what gives her the name. Arcane took 6 years to produce and cost more than many Hollywood films.',
    fr: 'Le vrai nom de Jinx est Powder. Sa transformation psychologique en Jinx lui donne son surnom. Arcane a pris 6 ans à produire et a coûté plus cher que de nombreux films hollywoodiens.',
    pt: 'O nome real de Jinx é Powder. A sua transformação psicológica em Jinx é o que lhe dá o nome. Arcane demorou 6 anos a produzir e custou mais do que muitos filmes de Hollywood.',
  },
  'vi-arcane': {
    es: 'Vi y Jinx son hermanas, y en el juego League of Legends sus runas siempre fueron opuestas: Jinx causa caos, Vi impone orden. La serie Arcane tardó 11 años en llegar desde que los fans pedían el lore.',
    en: 'Vi and Jinx are sisters, and their League of Legends lore runes were always opposites: Jinx causes chaos, Vi enforces order. Arcane took 11 years to arrive after fans started asking for the lore.',
    fr: 'Vi et Jinx sont sœurs, et leurs runes de lore dans League of Legends ont toujours été opposées : Jinx cause le chaos, Vi impose l\'ordre. Arcane a mis 11 ans à arriver après que les fans ont demandé le lore.',
    pt: 'Vi e Jinx são irmãs, e as suas runas de lore em League of Legends sempre foram opostas: Jinx causa caos, Vi impõe ordem. Arcane demorou 11 anos a chegar depois de os fãs pedirem o lore.',
  },
  'joel-tlou': {
    es: 'Joel lleva el mismo reloj en la muñeca izquierda en todos los flashbacks. Es el reloj que su hija Sarah le dio. Nunca se menciona, nunca se señala. Pero está siempre ahí.',
    en: 'Joel wears the same watch on his left wrist in every flashback — the one his daughter Sarah gave him. It\'s never mentioned, never pointed out. But it\'s always there.',
    fr: 'Joel porte la même montre au poignet gauche dans chaque flashback — celle que sa fille Sarah lui a donnée. Cela n\'est jamais mentionné, jamais souligné. Mais elle est toujours là.',
    pt: 'Joel usa o mesmo relógio no pulso esquerdo em cada flashback — o que a sua filha Sarah lhe deu. Nunca é mencionado, nunca apontado. Mas está sempre lá.',
  },
  'darth-vader': {
    es: '"Vader" en holandés significa "padre". George Lucas siempre dice que fue coincidencia. Nadie en el universo entero le cree, y él lo sabe.',
    en: '"Vader" means "father" in Dutch. George Lucas always says it was a coincidence. Nobody in the entire universe believes him, and he knows it.',
    fr: '"Vader" signifie "père" en néerlandais. George Lucas dit toujours que c\'était une coïncidence. Personne dans l\'univers entier ne le croit, et il le sait.',
    pt: '"Vader" significa "pai" em holandês. George Lucas sempre diz que foi coincidência. Ninguém no universo inteiro acredita nele, e ele sabe disso.',
  },
  'yoda': {
    es: 'Yoda habla con el verbo al final de la frase porque así funciona la gramática clásica japonesa. George Lucas se inspiró en maestros de artes marciales japoneses para crear su forma de hablar.',
    en: 'Yoda speaks with the verb at the end of sentences because that\'s how classical Japanese grammar works. George Lucas modeled his speech patterns on Japanese martial arts masters.',
    fr: 'Yoda parle avec le verbe à la fin des phrases parce que c\'est ainsi que fonctionne la grammaire japonaise classique. George Lucas s\'est inspiré des maîtres d\'arts martiaux japonais pour créer son façon de parler.',
    pt: 'Yoda fala com o verbo no final das frases porque é assim que funciona a gramática japonesa clássica. George Lucas inspirou-se em mestres de artes marciais japoneses para criar a sua forma de falar.',
  },
  'jack-sparrow': {
    es: 'Johnny Depp modeló a Jack Sparrow en Keith Richards de los Rolling Stones y en un gato borracho. El estudio Disney odiaba el personaje hasta que vieron el montaje final. El resto es historia de taquilla.',
    en: 'Johnny Depp modeled Jack Sparrow on Keith Richards and a drunk cat. Disney executives hated the character until they saw the final cut. The rest is box office history.',
    fr: 'Johnny Depp a modélisé Jack Sparrow sur Keith Richards des Rolling Stones et sur un chat ivre. Les dirigeants de Disney détestaient le personnage jusqu\'à ce qu\'ils voient le montage final.',
    pt: 'Johnny Depp modelou Jack Sparrow em Keith Richards dos Rolling Stones e num gato bêbado. Os executivos da Disney odiavam a personagem até verem a montagem final. O resto é história de bilheteira.',
  },
  'shrek': {
    es: 'Mike Myers grabó todas las frases de Shrek en acento escocés en una segunda sesión, después de haberlas grabado en su voz normal. El cambio costó 4 millones de dólares adicionales. Y valió cada euro.',
    en: 'Mike Myers re-recorded all of Shrek\'s lines with a Scottish accent in a second session, after recording them in his normal voice first. The change cost an extra $4 million. Worth every penny.',
    fr: 'Mike Myers a réenregistré toutes les répliques de Shrek avec un accent écossais lors d\'une deuxième session, après les avoir enregistrées avec sa voix normale. Le changement a coûté 4 millions de dollars supplémentaires.',
    pt: 'Mike Myers regravou todas as falas do Shrek com sotaque escocês numa segunda sessão, depois de as ter gravado com a sua voz normal. A mudança custou 4 milhões de dólares adicionais. Valeu cada cêntimo.',
  },
  'gandalf': {
    es: 'Tolkien modeló a Gandalf en una postal de un anciano con sombrero apoyado en un árbol que tenía en su escritorio. La postal se llamaba "Der Berggeist" (El Espíritu de la Montaña). Era una reproducción de un cuadro alemán del siglo XIX.',
    en: 'Tolkien modeled Gandalf on a postcard of an old man in a hat leaning on a tree that sat on his desk. The postcard was called "Der Berggeist" (The Mountain Spirit) — a reproduction of a 19th century German painting.',
    fr: 'Tolkien a modelé Gandalf sur une carte postale d\'un vieil homme avec un chapeau appuyé sur un arbre qu\'il gardait sur son bureau. La carte postale s\'appelait "Der Berggeist" (L\'Esprit de la Montagne).',
    pt: 'Tolkien modelou Gandalf numa postal de um velho com chapéu apoiado numa árvore que tinha na sua secretária. A postal chamava-se "Der Berggeist" (O Espírito da Montanha) — uma reprodução de uma pintura alemã do século XIX.',
  },
  'frodo': {
    es: 'Los pies peludos de los hobbits se inspiraron en las liebres árticas, que tienen mucho pelo en las patas para caminar sobre la nieve. Tolkien era biológicamente muy preciso aunque viviera en la fantasía.',
    en: 'Hobbit hairy feet were inspired by Arctic hares, which have lots of fur on their feet for walking on snow. Tolkien was biologically very precise even while living in fantasy.',
    fr: 'Les pieds velus des hobbits ont été inspirés par les lièvres arctiques, qui ont beaucoup de fourrure sur les pattes pour marcher sur la neige. Tolkien était très précis biologiquement.',
    pt: 'Os pés peludos dos hobbits foram inspirados nas lebres árticas, que têm muito pelo nas patas para andar na neve. Tolkien era biologicamente muito preciso mesmo vivendo na fantasia.',
  },
  'walter-white': {
    es: 'Bryan Cranston visitó laboratorios reales de la DEA para preparar el papel. Los agentes le dijeron que el cristal azul del show era "demasiado puro para ser real". Vince Gilligan lo tomó como un cumplido.',
    en: 'Bryan Cranston visited real DEA labs to prepare for the role. Agents told him the blue crystal in the show was "too pure to be real." Vince Gilligan took that as a compliment.',
    fr: 'Bryan Cranston a visité de vrais laboratoires de la DEA pour préparer le rôle. Des agents lui ont dit que le cristal bleu du show était "trop pur pour être réel". Vince Gilligan l\'a pris comme un compliment.',
    pt: 'Bryan Cranston visitou laboratórios reais da DEA para se preparar para o papel. Os agentes disseram-lhe que o cristal azul do show era "puro a mais para ser real". Vince Gilligan levou isso como um elogio.',
  },
  'eleven': {
    es: 'Millie Bobby Brown nunca tuvo que actuar con efectos especiales reales: todo lo que mueve con la mente en el rodaje no existía. Sus reacciones a cosas invisibles son actuación pura. A los 12 años.',
    en: 'Millie Bobby Brown never had real special effects to act against — everything she moves with her mind didn\'t exist on set. Her reactions to invisible things are pure acting. At age 12.',
    fr: 'Millie Bobby Brown n\'a jamais eu d\'effets spéciaux réels contre lesquels jouer — tout ce qu\'elle déplace par l\'esprit n\'existait pas sur le plateau. Ses réactions à des choses invisibles sont du jeu pur. À 12 ans.',
    pt: 'Millie Bobby Brown nunca teve efeitos especiais reais para atuar — tudo o que move com a mente não existia no set. As suas reações a coisas invisíveis são atuação pura. Aos 12 anos.',
  },
  'wednesday-addams': {
    es: 'La familia Addams fue creada como sátira de la familia perfecta estadounidense de los años 60. Charles Addams dijo que los llamó así "porque eran como todo el mundo, pero al revés". La idea más honesta de la historia del cómic.',
    en: 'The Addams Family was created as a satire of the perfect American family of the 1960s. Charles Addams said he named them that "because they were like everyone else, just backwards." The most honest idea in comic history.',
    fr: 'La famille Addams a été créée comme une satire de la famille américaine parfaite des années 1960. Charles Addams a dit qu\'il les a ainsi nommés "parce qu\'ils étaient comme tout le monde, juste à l\'envers".',
    pt: 'A Família Addams foi criada como sátira da família americana perfeita dos anos 60. Charles Addams disse que os chamou assim "porque eram como toda a gente, só que ao contrário".',
  },
  'lupin': {
    es: 'Arsène Lupin apareció por primera vez en 1905 y tiene más de 24 novelas originales. Omar Sy confesó que de niño en Senegal se identificaba más con Lupin que con cualquier otro héroe occidental.',
    en: 'Arsène Lupin first appeared in 1905 and has over 24 original novels. Omar Sy confessed that as a child in Senegal, he identified more with Lupin than any other Western hero.',
    fr: 'Arsène Lupin est apparu pour la première fois en 1905 et compte plus de 24 romans originaux. Omar Sy a confessé qu\'enfant au Sénégal, il s\'identifiait plus à Lupin qu\'à tout autre héros occidental.',
    pt: 'Arsène Lupin apareceu pela primeira vez em 1905 e tem mais de 24 romances originais. Omar Sy confessou que em criança no Senegal se identificava mais com Lupin do que com qualquer outro herói ocidental.',
  },
  'steve-games': {
    es: 'Steve Harrington de Stranger Things fue escrito para morir en la primera temporada. Los guionistas lo salvaron porque Joe Keery lo hacía tan bien. A veces los actores escriben la historia sin saberlo.',
    en: 'Steve Harrington from Stranger Things was written to die in Season 1. The writers kept him alive because Joe Keery was doing such a great job. Sometimes actors write the story without knowing it.',
    fr: 'Steve Harrington de Stranger Things était censé mourir dans la saison 1. Les scénaristes l\'ont gardé en vie parce que Joe Keery faisait un si bon travail. Parfois les acteurs écrivent l\'histoire sans le savoir.',
    pt: 'Steve Harrington de Stranger Things foi escrito para morrer na 1ª temporada. Os guionistas mantiveram-no vivo porque Joe Keery estava a fazer um trabalho tão bom. Às vezes os atores escrevem a história sem saber.',
  },
  'dream-smp': {
    es: 'Dream fue uno de los canales de Minecraft de más rápido crecimiento en la historia de YouTube. Su cara fue un misterio durante años: cuando la reveló en 2023, el evento fue tendencia mundial.',
    en: 'Dream was one of the fastest-growing Minecraft channels in YouTube history. His face was a mystery for years — when he finally revealed it in 2023, the event trended worldwide.',
    fr: 'Dream a été l\'une des chaînes Minecraft à croissance la plus rapide de l\'histoire de YouTube. Son visage a été un mystère pendant des années — quand il l\'a révélé en 2023, l\'événement a été en tendance mondiale.',
    pt: 'Dream foi um dos canais de Minecraft de crescimento mais rápido na história do YouTube. O seu rosto foi um mistério durante anos — quando o revelou em 2023, o evento foi tendência mundial.',
  },
  'technoblade': {
    es: 'Technoblade ganó el torneo Potato Wars de Minecraft cosechando más de 400 millones de patatas virtuales. Literalmente. Y cuando murió en 2022, dejó un vídeo de despedida que rompió internet. Technoblade never dies.',
    en: 'Technoblade won the Minecraft Potato Wars tournament by harvesting over 400 million virtual potatoes. Literally. When he passed away in 2022, his farewell video broke the internet. Technoblade never dies.',
    fr: 'Technoblade a remporté le tournoi Potato Wars de Minecraft en récoltant plus de 400 millions de pommes de terre virtuelles. Littéralement. Quand il est décédé en 2022, sa vidéo d\'adieu a brisé internet.',
    pt: 'Technoblade ganhou o torneio Potato Wars do Minecraft colhendo mais de 400 milhões de batatas virtuais. Literalmente. Quando faleceu em 2022, o seu vídeo de despedida quebrou a internet. Technoblade never dies.',
  },
  'philza': {
    es: 'Philza mantuvo una partida de supervivencia de Minecraft durante 5 años sin morir. La terminó en directo con 20.000 personas viéndolo: una araña, un bebé zombie y la falta de leche. Cinco años. En 30 segundos.',
    en: 'Philza ran a Minecraft Hardcore world for 5 years without dying. It ended live with 20,000 viewers watching: a spider, a baby zombie, and the absence of milk. Five years. Thirty seconds.',
    fr: 'Philza a maintenu un monde Minecraft Hardcore pendant 5 ans sans mourir. Ça s\'est terminé en direct avec 20 000 spectateurs : une araignée, un bébé zombie et l\'absence de lait. Cinq ans. Trente secondes.',
    pt: 'Philza manteve um mundo Minecraft Hardcore durante 5 anos sem morrer. Terminou em direto com 20.000 espectadores: uma aranha, um bebé zombie e a ausência de leite. Cinco anos. Trinta segundos.',
  },
  'ibai': {
    es: 'Ibai Llanos organiza la Velada del Año, un torneo de boxeo entre creadores que bate récords cada edición. En 2024 superó los 4 millones de espectadores simultáneos, más que muchos eventos deportivos profesionales.',
    en: 'Ibai Llanos organizes La Velada del Año, a boxing tournament between creators that breaks records every year. In 2024 it surpassed 4 million simultaneous viewers — more than many professional sporting events.',
    fr: 'Ibai Llanos organise La Velada del Año, un tournoi de boxe entre créateurs qui bat des records à chaque édition. En 2024, il a dépassé les 4 millions de spectateurs simultanés.',
    pt: 'Ibai Llanos organiza a Velada del Año, um torneio de boxe entre criadores que bate recordes a cada edição. Em 2024 superou os 4 milhões de espectadores simultâneos.',
  },
  'rubius': {
    es: 'Rubius publicó su primer vídeo en 2011 con 17 años y fue uno de los primeros youtubers españoles en alcanzar millones de suscriptores. Creó el personaje de "El Rubius" antes de saber que eso tenía nombre.',
    en: 'Rubius posted his first video in 2011 at age 17 and became one of the first Spanish YouTubers to reach millions of subscribers. He created the "El Rubius" character before he even knew that had a name.',
    fr: 'Rubius a posté sa première vidéo en 2011 à 17 ans et est devenu l\'un des premiers YouTubers espagnols à atteindre des millions d\'abonnés. Il a créé le personnage "El Rubius" avant de savoir que ça s\'appelait comme ça.',
    pt: 'Rubius publicou o seu primeiro vídeo em 2011 com 17 anos e tornou-se um dos primeiros youtubers espanhóis a atingir milhões de subscritores. Criou o personagem "El Rubius" antes de saber que isso tinha nome.',
  },
  'among-us-red': {
    es: 'Among Us se lanzó en 2018 y durante dos años nadie lo jugó. En el verano de 2020, con millones de personas confinadas en casa, se convirtió en el juego más descargado del mundo casi de un día para otro.',
    en: 'Among Us launched in 2018 and went unplayed for two years. Then in summer 2020, with millions stuck at home, it became the most downloaded game in the world almost overnight.',
    fr: 'Among Us est sorti en 2018 et n\'a été joué par personne pendant deux ans. Puis à l\'été 2020, avec des millions de personnes confinées, il est devenu le jeu le plus téléchargé au monde presque du jour au lendemain.',
    pt: 'Among Us lançou em 2018 e ficou sem ser jogado durante dois anos. Depois, no verão de 2020, com milhões de pessoas confinadas, tornou-se o jogo mais descarregado do mundo quase de um dia para o outro.',
  },
  'sus-crewmate': {
    es: 'La palabra "sus" del Among Us (abreviatura de "sospechoso") entró en el diccionario de slang en inglés. El creador del juego dijo que no entendía muy bien por qué se hizo tan famoso. Nadie lo entiende. Eso también es parte del meme.',
    en: 'The word "sus" from Among Us (short for "suspicious") entered the English slang dictionary. The game\'s creator said he didn\'t really understand why it got so famous. Nobody does. That\'s also part of the meme.',
    fr: 'Le mot "sus" d\'Among Us (abréviation de "suspicious") est entré dans le dictionnaire d\'argot anglais. Le créateur du jeu a dit qu\'il ne comprenait pas vraiment pourquoi c\'était devenu si célèbre.',
    pt: 'A palavra "sus" do Among Us (abreviatura de "suspeito") entrou no dicionário de calão inglês. O criador do jogo disse que não entendia muito bem por que razão se tornou tão famoso.',
  },
  'herobrine': {
    es: 'Herobrine nunca ha existido en Minecraft. Es un creepypasta inventado en 2010. Pero Mojang continuó añadiendo "Removed Herobrine" en los changelogs de actualizaciones durante años, como broma interna para los fans.',
    en: 'Herobrine has never existed in Minecraft. He\'s a creepypasta invented in 2010. But Mojang kept adding "Removed Herobrine" to update changelogs for years as an inside joke for fans.',
    fr: 'Herobrine n\'a jamais existé dans Minecraft. C\'est un creepypasta inventé en 2010. Mais Mojang a continué à ajouter "Removed Herobrine" dans les changelogs de mises à jour pendant des années, comme blague interne.',
    pt: 'Herobrine nunca existiu no Minecraft. É um creepypasta inventado em 2010. Mas a Mojang continuou a adicionar "Removed Herobrine" nos changelogs de atualizações durante anos, como piada interna para os fãs.',
  },
  'creeper-humano': {
    es: 'El Creeper fue creado por accidente. Notch intentó programar un cerdo y confundió el alto con el ancho en el código. El resultado fue tan inquietante que lo dejó en el juego. El error más icónico de la historia de los videojuegos.',
    en: 'The Creeper was created by accident. Notch tried to program a pig and swapped height and width in the code. The result was so unsettling he kept it. The most iconic coding mistake in gaming history.',
    fr: 'Le Creeper a été créé par accident. Notch essayait de programmer un cochon et a interchangé la hauteur et la largeur dans le code. Le résultat était si inquiétant qu\'il l\'a gardé.',
    pt: 'O Creeper foi criado por acidente. Notch tentou programar um porco e trocou a altura pela largura no código. O resultado era tão perturbador que o manteve. O erro de programação mais icónico da história dos jogos.',
  },
  'enderman-humano': {
    es: 'El Enderman se inspiró en el Slender Man, el creepypasta de internet creado en 2009. Sus proporciones alargadas, su comportamiento impredecible y que te ataque si lo miras son referencias directas al mito.',
    en: 'The Enderman was inspired by Slender Man, the internet creepypasta created in 2009. Its elongated proportions, unpredictable behavior, and attacking you when you look at it are direct references to the myth.',
    fr: 'L\'Enderman s\'est inspiré du Slender Man, le creepypasta internet créé en 2009. Ses proportions allongées, son comportement imprévisible et le fait qu\'il vous attaque si vous le regardez sont des références directes au mythe.',
    pt: 'O Enderman foi inspirado no Slender Man, o creepypasta da internet criado em 2009. As suas proporções alongadas, comportamento imprevisível e atacar quando o olhas são referências diretas ao mito.',
  },
  'notch': {
    es: 'Markus Persson (Notch) creó la primera versión jugable de Minecraft en una semana. La vendió por 2.500 millones de dólares a Microsoft en 2014. Luego tuiteó que se sentía solo. El dinero no compra todo, ni en Minecraft.',
    en: 'Markus Persson (Notch) built the first playable version of Minecraft in one week. He sold it to Microsoft for $2.5 billion in 2014. Then he tweeted he felt lonely. Money doesn\'t buy everything, not even in Minecraft.',
    fr: 'Markus Persson (Notch) a créé la première version jouable de Minecraft en une semaine. Il l\'a vendu à Microsoft pour 2,5 milliards de dollars en 2014. Puis il a tweeté qu\'il se sentait seul.',
    pt: 'Markus Persson (Notch) criou a primeira versão jogável do Minecraft numa semana. Vendeu-a à Microsoft por 2,5 mil milhões de dólares em 2014. Depois tweetou que se sentia sozinho. O dinheiro não compra tudo.',
  },
  'denji': {
    es: 'Denji tiene dos grandes sueños en la vida: comer pan con mermelada y abrazar a una chica. Dado su trabajo como cazademonios, ambas cosas resultan ser sorprendentemente complicadas de conseguir.',
    en: 'Denji has two great dreams in life: eating jam bread and hugging a girl. Given his job as a devil hunter, both turn out to be surprisingly difficult to achieve.',
    fr: 'Denji a deux grands rêves dans la vie : manger du pain à la confiture et serrer une fille dans ses bras. Vu son travail de chasseur de démons, les deux s\'avèrent étonnamment difficiles à réaliser.',
    pt: 'Denji tem dois grandes sonhos na vida: comer pão com doce e abraçar uma rapariga. Dado o seu trabalho como caçador de demónios, ambos se revelam surpreendentemente difíceis de conseguir.',
  },
  'makima': {
    es: 'Makima casi nunca parpadea en la serie. No es un fallo de animación: los animadores lo hicieron deliberadamente para que pareciera menos humana. Si te fijas en los ojos, empiezas a entenderla.',
    en: 'Makima almost never blinks in the anime. That\'s not an animation error — the animators did it deliberately to make her seem less human. Pay attention to her eyes, and you\'ll start to understand her.',
    fr: 'Makima ne cligne presque jamais des yeux dans la série. Ce n\'est pas une erreur d\'animation : les animateurs l\'ont fait délibérément pour la faire paraître moins humaine.',
    pt: 'Makima quase nunca pisca os olhos na série. Não é um erro de animação: os animadores fizeram-no deliberadamente para a fazer parecer menos humana. Presta atenção aos olhos e começarás a entendê-la.',
  },
  'power-csm': {
    es: 'Power afirma ser el ser más poderoso del universo... y luego se asusta de los ratones. Es el personaje más caótico de Chainsaw Man y el que tiene menos filtro entre cerebro y boca. Un tesoro.',
    en: 'Power claims to be the most powerful being in the universe... and then gets scared of mice. She\'s the most chaotic character in Chainsaw Man, with zero filter between brain and mouth. An absolute treasure.',
    fr: 'Power prétend être l\'être le plus puissant de l\'univers... et a ensuite peur des souris. C\'est le personnage le plus chaotique de Chainsaw Man, avec zéro filtre entre cerveau et bouche.',
    pt: 'Power afirma ser o ser mais poderoso do universo... e depois assusta-se com ratos. É o personagem mais caótico de Chainsaw Man e aquele que tem menos filtro entre cérebro e boca.',
  },
  'anya-forger': {
    es: 'Anya fue creada en un laboratorio y es la única superviviente de un experimento que mató a todos los demás sujetos. La razón por la que puede leer mentes es ese precio. Spy x Family es adorable y perturbador a la vez.',
    en: 'Anya was created in a lab and is the only survivor of an experiment that killed all other subjects. Her mind-reading ability came at that cost. Spy x Family manages to be both adorable and deeply unsettling.',
    fr: 'Anya a été créée dans un laboratoire et est la seule survivante d\'une expérience qui a tué tous les autres sujets. Sa capacité à lire dans les pensées est le prix à payer. Spy x Family est à la fois adorable et profondément inquiétant.',
    pt: 'Anya foi criada num laboratório e é a única sobrevivente de uma experiência que matou todos os outros sujeitos. A sua capacidade de ler mentes custou esse preço. Spy x Family consegue ser adorável e perturbador ao mesmo tempo.',
  },
  'loid-forger': {
    es: 'El nombre real de Loid Forger es desconocido. "Loid Forger" es una identidad falsa: su nombre de agente es Crepúsculo. Básicamente es el padre más dedicado del mundo... para una misión que nunca termina.',
    en: 'Loid Forger\'s real name is unknown. "Loid Forger" is a fake identity — his agent name is Twilight. He\'s basically the world\'s most dedicated dad... for a mission that never ends.',
    fr: 'Le vrai nom de Loid Forger est inconnu. "Loid Forger" est une fausse identité — son nom d\'agent est Twilight. Il est fondamentalement le père le plus dévoué du monde... pour une mission qui ne se termine jamais.',
    pt: 'O nome real de Loid Forger é desconhecido. "Loid Forger" é uma identidade falsa — o seu nome de agente é Crepúsculo. É basicamente o pai mais dedicado do mundo... para uma missão que nunca termina.',
  },
  'sukuna': {
    es: 'Ryomen Sukuna fue un hechicero tan poderoso que cuando murió hace 1.000 años, nadie fue capaz de destruir su cuerpo. Lo partieron en 20 dedos y los esparcieron por el mundo. Eso es ser un jefe final de verdad.',
    en: 'Ryomen Sukuna was so powerful that when he died 1,000 years ago, no one could destroy his body. They split him into 20 fingers and scattered them across the world. That\'s how you become a true final boss.',
    fr: 'Ryomen Sukuna était si puissant que lorsqu\'il est mort il y a 1 000 ans, personne ne pouvait détruire son corps. Ils l\'ont divisé en 20 doigts et les ont dispersés dans le monde.',
    pt: 'Ryomen Sukuna era tão poderoso que quando morreu há 1.000 anos, ninguém conseguiu destruir o seu corpo. Dividiram-no em 20 dedos e espalharam-nos pelo mundo. É assim que se torna um verdadeiro boss final.',
  },
  'nezuko': {
    es: 'Nezuko no habla durante casi toda la serie porque lleva una mordaza de bambú. Su animadora dijo que diseñar sus expresiones de ojos y cejas para transmitir todo lo que dice sin boca fue el mayor reto de la producción.',
    en: 'Nezuko barely speaks throughout the series because of her bamboo muzzle. Her animator said designing her eye and eyebrow expressions to convey everything she feels without a mouth was the biggest challenge of the production.',
    fr: 'Nezuko parle à peine tout au long de la série à cause de son bâillon en bambou. Son animatrice a dit que concevoir ses expressions de yeux et de sourcils pour tout transmettre sans bouche était le plus grand défi de la production.',
    pt: 'Nezuko quase não fala durante toda a série por causa da sua mordaça de bambu. A sua animadora disse que desenhar as suas expressões de olhos e sobrancelhas para transmitir tudo sem boca foi o maior desafio da produção.',
  },
  'zenitsu': {
    es: 'Zenitsu solo conoce una técnica de combate: el Primer Trueno. Pero la ha perfeccionado hasta tal punto que es devastadora. Y solo puede usarla cuando está inconsciente de miedo. El héroe más honesto del anime.',
    en: 'Zenitsu only knows one combat technique: First Thunder. But he\'s perfected it to the point where it\'s devastating — and he can only use it when he\'s unconscious from fear. The most honest hero in anime.',
    fr: 'Zenitsu ne connaît qu\'une seule technique de combat : Premier Tonnerre. Mais il l\'a perfectionnée au point qu\'elle est dévastatrice — et il ne peut l\'utiliser que lorsqu\'il est inconscient de peur.',
    pt: 'Zenitsu só conhece uma técnica de combate: Primeiro Trovão. Mas aperfeiçoou-a ao ponto de ser devastadora — e só consegue usá-la quando está inconsciente de medo. O herói mais honesto do anime.',
  },
  'v-cyberpunk': {
    es: 'V en Cyberpunk 2077 nunca revela su nombre completo durante todo el juego. En la jerga de Night City, solo "V" es suficiente. El mayor secreto de una ciudad donde todos los secretos tienen precio.',
    en: 'V in Cyberpunk 2077 never reveals their full name throughout the entire game. In Night City slang, just "V" is enough. The biggest secret in a city where every secret has a price.',
    fr: 'V dans Cyberpunk 2077 ne révèle jamais son nom complet tout au long du jeu. Dans l\'argot de Night City, juste "V" suffit. Le plus grand secret d\'une ville où chaque secret a un prix.',
    pt: 'V em Cyberpunk 2077 nunca revela o seu nome completo durante todo o jogo. Na gíria de Night City, apenas "V" é suficiente. O maior segredo de uma cidade onde todos os segredos têm preço.',
  },
  'the-tarnished': {
    es: 'El Sin Gracia de Elden Ring no habla ni una sola vez en toda la historia. Todo el juego ocurre alrededor de un personaje que no dice absolutamente nada. Y aun así su historia emociona. FromSoftware es arte.',
    en: 'The Tarnished in Elden Ring never speaks once in the entire story. The whole game revolves around a character who says absolutely nothing. And yet their journey is deeply emotional. FromSoftware is art.',
    fr: 'Le Terni dans Elden Ring ne parle pas une seule fois dans toute l\'histoire. Tout le jeu tourne autour d\'un personnage qui ne dit absolument rien. Et pourtant leur voyage est profondément émouvant.',
    pt: 'O Sem Graça em Elden Ring nunca fala uma única vez em toda a história. Todo o jogo gira em torno de um personagem que não diz absolutamente nada. E ainda assim a sua jornada é profundamente emotiva.',
  },
  'aloy': {
    es: 'Aloy fue el primer personaje protagonista con captura de rostro digital con tal nivel de detalle que algunos jugadores pensaron que era una actriz real en las primeras imágenes del E3 2015. Sony tuvo que aclarar que era CGI.',
    en: 'Aloy was one of the first protagonists with facial capture so detailed that some players thought she was a real actress in the first E3 2015 screenshots. Sony had to clarify it was CGI.',
    fr: 'Aloy était l\'une des premières protagonistes avec une capture faciale si détaillée que certains joueurs ont pensé qu\'elle était une vraie actrice dans les premières captures d\'écran de l\'E3 2015.',
    pt: 'Aloy foi uma das primeiras protagonistas com captura facial tão detalhada que alguns jogadores pensaram que era uma atriz real nas primeiras imagens do E3 2015. A Sony teve de esclarecer que era CGI.',
  },
  '2b-nier': {
    es: '2B tiene prohibido emocionarse. Pero durante todo NieR: Automata está llena de emociones que suprime constantemente. Su frase más famosa: "Emotions are prohibited." La más triste también.',
    en: '2B is forbidden from feeling emotions. But throughout NieR: Automata she\'s full of emotions she constantly suppresses. Her most famous line: "Emotions are prohibited." Also her saddest.',
    fr: '2B a l\'interdiction de ressentir des émotions. Mais tout au long de NieR: Automata, elle est pleine d\'émotions qu\'elle supprime constamment. Sa phrase la plus célèbre : "Emotions are prohibited." Aussi la plus triste.',
    pt: '2B tem proibido sentir emoções. Mas ao longo de NieR: Automata está cheia de emoções que suprime constantemente. A sua frase mais famosa: "Emotions are prohibited." Também a mais triste.',
  },
  'gollum': {
    es: 'Gollum se llama así por el sonido que hace al tragar: "gollum, gollum". Su nombre original era Sméagol. Cuando Bilbo lo encontró, llevaba más de 500 años solo bajo tierra. Eso explica muchas cosas.',
    en: 'Gollum is named after the sound he makes when he swallows: "gollum, gollum." His original name was Sméagol. When Bilbo found him, he\'d been alone underground for over 500 years. That explains a lot.',
    fr: 'Gollum tire son nom du son qu\'il fait en avalant : "gollum, gollum". Son vrai nom était Sméagol. Quand Bilbo l\'a trouvé, il était seul sous terre depuis plus de 500 ans. Ça explique beaucoup de choses.',
    pt: 'Gollum tem o nome do som que faz ao engolir: "gollum, gollum". O seu nome original era Sméagol. Quando Bilbo o encontrou, estava sozinho debaixo da terra há mais de 500 anos. Isso explica muita coisa.',
  },
  'thanos-endgame': {
    es: 'En los cómics originales, Thanos elimina la mitad del universo para impresionar a la Muerte personificada, con quien está enamorado. En las películas se lo inventó él solo. ¿Cuál es más aterrador?',
    en: 'In the original comics, Thanos wipes out half the universe to impress the personification of Death, with whom he\'s in love. In the movies he came up with the idea himself. Which version is scarier?',
    fr: 'Dans les comics originaux, Thanos élimine la moitié de l\'univers pour impressionner la personnification de la Mort, dont il est amoureux. Dans les films, il a eu l\'idée tout seul. Quelle version est la plus terrifiante ?',
    pt: 'Nos quadrinhos originais, Thanos elimina metade do universo para impressionar a personificação da Morte, por quem está apaixonado. Nos filmes inventou a ideia sozinho. Qual é mais assustador?',
  },
}
