export type Locale = 'es' | 'en' | 'fr' | 'pt'

export interface GuideStep {
  title: string
  desc: string
}

export interface GuideContent {
  metaTitle: string
  metaDesc: string
  title: string
  intro: string
  steps: GuideStep[]
  tip: string
  tipLabel: string
  ctaTitle: string
  ctaBtn: string
}

export interface Guide {
  slug: string
  icon: string
  platformName: Record<Locale, string>
  content: Record<Locale, GuideContent>
}

export const GUIDES: Guide[] = [
  {
    slug: 'pc-java',
    icon: '🖥️',
    platformName: { es: 'PC – Java Edition', en: 'PC – Java Edition', fr: 'PC – Java Edition', pt: 'PC – Java Edition' },
    content: {
      es: {
        metaTitle: 'Cómo instalar tu skin en Minecraft Java Edition (PC) – MakeSkins',
        metaDesc: 'Guía paso a paso para instalar una skin personalizada en Minecraft Java Edition en Windows, Mac y Linux. Gratis y sin mods.',
        title: 'Cómo instalar tu skin en Minecraft Java Edition',
        intro: 'Minecraft Java Edition es la versión original para PC y Mac. Instalar una skin es muy sencillo y no necesitas ningún mod.',
        steps: [
          { title: 'Descarga tu skin', desc: 'Crea tu skin en MakeSkins y descarga el archivo .png en tu ordenador.' },
          { title: 'Abre el Minecraft Launcher', desc: 'Inicia el Minecraft Launcher. Asegúrate de estar conectado con tu cuenta de Microsoft u Mojang.' },
          { title: 'Ve a la sección Skins', desc: 'Haz clic en tu nombre de usuario arriba a la izquierda del launcher → selecciona la pestaña "Skins".' },
          { title: 'Añade tu skin', desc: 'Haz clic en el botón "+" para añadir una nueva skin. Ponle un nombre si quieres.' },
          { title: 'Sube el archivo', desc: 'Haz clic en "Examinar" o "Browse" y selecciona el archivo .png que descargaste de MakeSkins.' },
          { title: '¡Actívala!', desc: 'Haz clic en "Usar" o "Use". La próxima vez que entres al juego, todos verán tu nueva skin.' },
        ],
        tip: 'Tu skin se guarda en los servidores de Mojang y es visible para otros jugadores en servidores multijugador. Puedes tener varias skins guardadas y cambiar entre ellas cuando quieras.',
        tipLabel: '💡 Consejo',
        ctaTitle: '¿Aún no tienes tu skin?',
        ctaBtn: 'Crear mi skin gratis →',
      },
      en: {
        metaTitle: 'How to install your skin in Minecraft Java Edition (PC) – MakeSkins',
        metaDesc: 'Step-by-step guide to install a custom skin in Minecraft Java Edition on Windows, Mac and Linux. Free, no mods needed.',
        title: 'How to install your skin in Minecraft Java Edition',
        intro: 'Minecraft Java Edition is the original PC and Mac version. Installing a skin is very easy and requires no mods.',
        steps: [
          { title: 'Download your skin', desc: 'Create your skin on MakeSkins and download the .png file to your computer.' },
          { title: 'Open the Minecraft Launcher', desc: 'Launch the Minecraft Launcher and make sure you are logged in with your Microsoft or Mojang account.' },
          { title: 'Go to the Skins section', desc: 'Click your username in the top-left of the launcher → select the "Skins" tab.' },
          { title: 'Add your skin', desc: 'Click the "+" button to add a new skin. Give it a name if you like.' },
          { title: 'Upload the file', desc: 'Click "Browse" and select the .png file you downloaded from MakeSkins.' },
          { title: 'Activate it!', desc: 'Click "Use". Next time you enter the game, everyone will see your new skin.' },
        ],
        tip: 'Your skin is stored on Mojang\'s servers and is visible to other players on multiplayer servers. You can save multiple skins and switch between them at any time.',
        tipLabel: '💡 Tip',
        ctaTitle: "Don't have your skin yet?",
        ctaBtn: 'Create my skin for free →',
      },
      fr: {
        metaTitle: 'Comment installer ton skin sur Minecraft Java Edition (PC) – MakeSkins',
        metaDesc: 'Guide étape par étape pour installer un skin personnalisé sur Minecraft Java Edition sous Windows, Mac et Linux.',
        title: 'Comment installer ton skin sur Minecraft Java Edition',
        intro: "Minecraft Java Edition est la version originale pour PC et Mac. Installer un skin est très simple et ne nécessite aucun mod.",
        steps: [
          { title: 'Télécharge ton skin', desc: 'Crée ton skin sur MakeSkins et télécharge le fichier .png sur ton ordinateur.' },
          { title: 'Ouvre le Minecraft Launcher', desc: 'Lance le Minecraft Launcher et connecte-toi avec ton compte Microsoft ou Mojang.' },
          { title: 'Accède à la section Skins', desc: 'Clique sur ton nom en haut à gauche du launcher → sélectionne l\'onglet "Skins".' },
          { title: 'Ajoute ton skin', desc: 'Clique sur le bouton "+" pour ajouter un nouveau skin.' },
          { title: 'Importe le fichier', desc: 'Clique sur "Parcourir" et sélectionne le fichier .png téléchargé depuis MakeSkins.' },
          { title: 'Active-le !', desc: 'Clique sur "Utiliser". La prochaine fois que tu entres dans le jeu, tout le monde verra ton nouveau skin.' },
        ],
        tip: "Ton skin est enregistré sur les serveurs de Mojang et visible par les autres joueurs en multijoueur. Tu peux enregistrer plusieurs skins et changer à tout moment.",
        tipLabel: '💡 Astuce',
        ctaTitle: 'Tu n\'as pas encore ton skin ?',
        ctaBtn: 'Créer mon skin gratuitement →',
      },
      pt: {
        metaTitle: 'Como instalar sua skin no Minecraft Java Edition (PC) – MakeSkins',
        metaDesc: 'Guia passo a passo para instalar uma skin personalizada no Minecraft Java Edition no Windows, Mac e Linux.',
        title: 'Como instalar sua skin no Minecraft Java Edition',
        intro: 'O Minecraft Java Edition é a versão original para PC e Mac. Instalar uma skin é muito simples e não precisa de mods.',
        steps: [
          { title: 'Baixe sua skin', desc: 'Crie sua skin no MakeSkins e baixe o arquivo .png no seu computador.' },
          { title: 'Abra o Minecraft Launcher', desc: 'Inicie o Minecraft Launcher e certifique-se de estar logado com sua conta Microsoft ou Mojang.' },
          { title: 'Vá para a seção Skins', desc: 'Clique no seu nome no canto superior esquerdo do launcher → selecione a guia "Skins".' },
          { title: 'Adicione sua skin', desc: 'Clique no botão "+" para adicionar uma nova skin.' },
          { title: 'Faça upload do arquivo', desc: 'Clique em "Procurar" e selecione o arquivo .png baixado do MakeSkins.' },
          { title: 'Ative-a!', desc: 'Clique em "Usar". Na próxima vez que entrar no jogo, todos verão sua nova skin.' },
        ],
        tip: 'Sua skin fica salva nos servidores da Mojang e é visível para outros jogadores em servidores multiplayer. Você pode ter várias skins e trocar entre elas quando quiser.',
        tipLabel: '💡 Dica',
        ctaTitle: 'Ainda não tem sua skin?',
        ctaBtn: 'Criar minha skin grátis →',
      },
    },
  },
  {
    slug: 'pc-bedrock',
    icon: '🪟',
    platformName: { es: 'PC – Windows (Bedrock)', en: 'PC – Windows (Bedrock)', fr: 'PC – Windows (Bedrock)', pt: 'PC – Windows (Bedrock)' },
    content: {
      es: {
        metaTitle: 'Cómo instalar tu skin en Minecraft Windows 10/11 (Bedrock) – MakeSkins',
        metaDesc: 'Tutorial para poner una skin personalizada en Minecraft Bedrock Edition para Windows 10 y Windows 11.',
        title: 'Cómo instalar tu skin en Minecraft para Windows (Bedrock)',
        intro: 'Minecraft para Windows (también llamado Bedrock Edition) es la versión disponible en la Microsoft Store. El proceso es ligeramente diferente a Java.',
        steps: [
          { title: 'Descarga tu skin', desc: 'Crea tu skin en MakeSkins y descarga el archivo .png en tu ordenador.' },
          { title: 'Abre Minecraft', desc: 'Inicia Minecraft para Windows desde la Microsoft Store o el Xbox Game Pass.' },
          { title: 'Ve a tu perfil', desc: 'En el menú principal, haz clic en el icono de tu personaje (esquina superior izquierda) o busca "Editar personaje".' },
          { title: 'Selecciona Skins clásicas', desc: 'En el editor de personaje, busca la pestaña "Skins clásicas" (Classic Skins). Es diferente del creador de personaje normal.' },
          { title: 'Elige tu skin', desc: 'Haz clic en "Elegir nuevo skin" → "Examinar archivos" → selecciona tu .png descargado.' },
          { title: 'Confirma el modelo', desc: 'Elige el modelo: Steve (brazos anchos) o Alex (brazos delgados). Pulsa "Confirmar".' },
        ],
        tip: 'Si juegas en varios dispositivos Bedrock (Xbox, móvil, Switch), puedes sincronizar tu skin en todos desde minecraft.net con tu cuenta de Microsoft.',
        tipLabel: '💡 Consejo',
        ctaTitle: '¿Aún no tienes tu skin?',
        ctaBtn: 'Crear mi skin gratis →',
      },
      en: {
        metaTitle: 'How to install your skin in Minecraft Windows 10/11 (Bedrock) – MakeSkins',
        metaDesc: 'Tutorial to set a custom skin in Minecraft Bedrock Edition for Windows 10 and Windows 11.',
        title: 'How to install your skin in Minecraft for Windows (Bedrock)',
        intro: 'Minecraft for Windows (also called Bedrock Edition) is the version available on the Microsoft Store. The process is slightly different from Java.',
        steps: [
          { title: 'Download your skin', desc: 'Create your skin on MakeSkins and download the .png file to your computer.' },
          { title: 'Open Minecraft', desc: 'Launch Minecraft for Windows from the Microsoft Store or Xbox Game Pass.' },
          { title: 'Go to your profile', desc: 'On the main menu, click the character icon (top-left corner) or find "Edit character".' },
          { title: 'Select Classic Skins', desc: 'In the character editor, look for the "Classic Skins" tab — it\'s separate from the regular character creator.' },
          { title: 'Choose your skin', desc: 'Click "Choose new skin" → "Browse files" → select your downloaded .png file.' },
          { title: 'Confirm the model', desc: 'Choose the model: Steve (wide arms) or Alex (slim arms). Click "Confirm".' },
        ],
        tip: 'If you play on multiple Bedrock devices (Xbox, mobile, Switch), you can sync your skin across all of them from minecraft.net using your Microsoft account.',
        tipLabel: '💡 Tip',
        ctaTitle: "Don't have your skin yet?",
        ctaBtn: 'Create my skin for free →',
      },
      fr: {
        metaTitle: 'Comment installer ton skin sur Minecraft Windows 10/11 (Bedrock) – MakeSkins',
        metaDesc: 'Tutoriel pour mettre un skin personnalisé sur Minecraft Bedrock Edition pour Windows 10 et Windows 11.',
        title: 'Comment installer ton skin sur Minecraft pour Windows (Bedrock)',
        intro: "Minecraft pour Windows (aussi appelé Bedrock Edition) est disponible sur le Microsoft Store. Le processus est légèrement différent de Java.",
        steps: [
          { title: 'Télécharge ton skin', desc: 'Crée ton skin sur MakeSkins et télécharge le fichier .png sur ton ordinateur.' },
          { title: 'Ouvre Minecraft', desc: 'Lance Minecraft pour Windows depuis le Microsoft Store ou Xbox Game Pass.' },
          { title: 'Accède à ton profil', desc: 'Dans le menu principal, clique sur l\'icône de ton personnage (coin supérieur gauche).' },
          { title: 'Sélectionne Skins classiques', desc: 'Dans l\'éditeur de personnage, cherche l\'onglet "Skins classiques" — séparé du créateur de personnage habituel.' },
          { title: 'Choisis ton skin', desc: 'Clique sur "Choisir un nouveau skin" → "Parcourir les fichiers" → sélectionne ton fichier .png.' },
          { title: 'Confirme le modèle', desc: 'Choisis le modèle : Steve (bras larges) ou Alex (bras fins). Clique sur "Confirmer".' },
        ],
        tip: "Si tu joues sur plusieurs appareils Bedrock (Xbox, mobile, Switch), tu peux synchroniser ton skin depuis minecraft.net avec ton compte Microsoft.",
        tipLabel: '💡 Astuce',
        ctaTitle: 'Tu n\'as pas encore ton skin ?',
        ctaBtn: 'Créer mon skin gratuitement →',
      },
      pt: {
        metaTitle: 'Como instalar sua skin no Minecraft Windows 10/11 (Bedrock) – MakeSkins',
        metaDesc: 'Tutorial para colocar uma skin personalizada no Minecraft Bedrock Edition para Windows 10 e Windows 11.',
        title: 'Como instalar sua skin no Minecraft para Windows (Bedrock)',
        intro: 'O Minecraft para Windows (também chamado de Bedrock Edition) está disponível na Microsoft Store. O processo é um pouco diferente do Java.',
        steps: [
          { title: 'Baixe sua skin', desc: 'Crie sua skin no MakeSkins e baixe o arquivo .png no seu computador.' },
          { title: 'Abra o Minecraft', desc: 'Inicie o Minecraft para Windows pela Microsoft Store ou Xbox Game Pass.' },
          { title: 'Vá ao seu perfil', desc: 'No menu principal, clique no ícone do personagem (canto superior esquerdo).' },
          { title: 'Selecione Skins Clássicas', desc: 'No editor de personagem, procure a aba "Skins Clássicas" — separada do criador normal.' },
          { title: 'Escolha sua skin', desc: 'Clique em "Escolher nova skin" → "Procurar arquivos" → selecione seu arquivo .png.' },
          { title: 'Confirme o modelo', desc: 'Escolha o modelo: Steve (braços largos) ou Alex (braços finos). Clique em "Confirmar".' },
        ],
        tip: 'Se você joga em vários dispositivos Bedrock (Xbox, celular, Switch), pode sincronizar sua skin em todos pelo minecraft.net com sua conta Microsoft.',
        tipLabel: '💡 Dica',
        ctaTitle: 'Ainda não tem sua skin?',
        ctaBtn: 'Criar minha skin grátis →',
      },
    },
  },
  {
    slug: 'xbox',
    icon: '🎮',
    platformName: { es: 'Xbox', en: 'Xbox', fr: 'Xbox', pt: 'Xbox' },
    content: {
      es: {
        metaTitle: 'Cómo poner una skin personalizada en Minecraft para Xbox – MakeSkins',
        metaDesc: 'Guía para instalar tu propia skin en Minecraft para Xbox One y Xbox Series X|S. Método sencillo con cuenta Microsoft.',
        title: 'Cómo instalar tu skin en Minecraft para Xbox',
        intro: 'En Xbox, Minecraft usa la edición Bedrock. La forma más sencilla es sincronizar tu skin a través de tu cuenta de Microsoft, sin necesidad de USB.',
        steps: [
          { title: 'Descarga tu skin en el móvil u ordenador', desc: 'Crea tu skin en MakeSkins desde tu teléfono o PC y descarga el archivo .png.' },
          { title: 'Ve a minecraft.net', desc: 'Abre un navegador en tu teléfono o PC y ve a minecraft.net. Inicia sesión con la misma cuenta de Microsoft que usas en tu Xbox.' },
          { title: 'Ve a tu perfil', desc: 'Haz clic en tu nombre arriba a la derecha → "Mi perfil" → "Cambiar apariencia".' },
          { title: 'Sube tu skin', desc: 'Selecciona "Subir skin" → elige el archivo .png descargado de MakeSkins → elige modelo Steve o Alex.' },
          { title: 'Guarda los cambios', desc: 'Pulsa "Guardar". La skin queda vinculada a tu cuenta de Microsoft.' },
          { title: 'Abre Minecraft en Xbox', desc: 'Enciende tu Xbox y abre Minecraft. La skin se sincroniza automáticamente al iniciar sesión. ¡Listo!' },
        ],
        tip: 'Esta sincronización funciona para todos tus dispositivos Bedrock a la vez: Xbox, móvil, Switch y Windows. Con un solo cambio, tu skin se actualiza en todas partes.',
        tipLabel: '💡 Consejo',
        ctaTitle: '¿Aún no tienes tu skin?',
        ctaBtn: 'Crear mi skin gratis →',
      },
      en: {
        metaTitle: 'How to set a custom skin in Minecraft for Xbox – MakeSkins',
        metaDesc: 'Guide to install your own skin in Minecraft for Xbox One and Xbox Series X|S. Easy method using your Microsoft account.',
        title: 'How to install your skin in Minecraft for Xbox',
        intro: 'On Xbox, Minecraft uses the Bedrock edition. The easiest way is to sync your skin through your Microsoft account — no USB needed.',
        steps: [
          { title: 'Download your skin on phone or PC', desc: 'Create your skin on MakeSkins from your phone or PC and download the .png file.' },
          { title: 'Go to minecraft.net', desc: 'Open a browser on your phone or PC and go to minecraft.net. Sign in with the same Microsoft account you use on Xbox.' },
          { title: 'Go to your profile', desc: 'Click your name top-right → "My Profile" → "Change Appearance".' },
          { title: 'Upload your skin', desc: 'Select "Upload skin" → choose the .png file downloaded from MakeSkins → choose Steve or Alex model.' },
          { title: 'Save your changes', desc: 'Click "Save". The skin is now linked to your Microsoft account.' },
          { title: 'Open Minecraft on Xbox', desc: 'Turn on your Xbox and open Minecraft. The skin syncs automatically when you sign in. Done!' },
        ],
        tip: 'This sync works for all your Bedrock devices at once: Xbox, mobile, Switch and Windows. One change updates your skin everywhere.',
        tipLabel: '💡 Tip',
        ctaTitle: "Don't have your skin yet?",
        ctaBtn: 'Create my skin for free →',
      },
      fr: {
        metaTitle: 'Comment mettre un skin personnalisé sur Minecraft pour Xbox – MakeSkins',
        metaDesc: 'Guide pour installer ton propre skin sur Minecraft pour Xbox One et Xbox Series X|S. Méthode simple avec compte Microsoft.',
        title: 'Comment installer ton skin sur Minecraft pour Xbox',
        intro: "Sur Xbox, Minecraft utilise l'édition Bedrock. La méthode la plus simple est de synchroniser ton skin via ton compte Microsoft — sans USB.",
        steps: [
          { title: 'Télécharge ton skin sur téléphone ou PC', desc: 'Crée ton skin sur MakeSkins depuis ton téléphone ou PC et télécharge le fichier .png.' },
          { title: 'Va sur minecraft.net', desc: 'Ouvre un navigateur sur ton téléphone ou PC et connecte-toi sur minecraft.net avec le même compte Microsoft que ta Xbox.' },
          { title: 'Accède à ton profil', desc: 'Clique sur ton nom en haut à droite → "Mon profil" → "Changer d\'apparence".' },
          { title: 'Importe ton skin', desc: 'Sélectionne "Importer un skin" → choisis le fichier .png téléchargé depuis MakeSkins → choisis Steve ou Alex.' },
          { title: 'Sauvegarde', desc: 'Clique sur "Sauvegarder". Le skin est maintenant lié à ton compte Microsoft.' },
          { title: 'Ouvre Minecraft sur Xbox', desc: 'Allume ta Xbox et lance Minecraft. Le skin se synchronise automatiquement à la connexion. Terminé !' },
        ],
        tip: "Cette synchronisation fonctionne pour tous tes appareils Bedrock en même temps : Xbox, mobile, Switch et Windows. Un seul changement met à jour ton skin partout.",
        tipLabel: '💡 Astuce',
        ctaTitle: 'Tu n\'as pas encore ton skin ?',
        ctaBtn: 'Créer mon skin gratuitement →',
      },
      pt: {
        metaTitle: 'Como colocar uma skin personalizada no Minecraft para Xbox – MakeSkins',
        metaDesc: 'Guia para instalar sua própria skin no Minecraft para Xbox One e Xbox Series X|S. Método simples com conta Microsoft.',
        title: 'Como instalar sua skin no Minecraft para Xbox',
        intro: 'No Xbox, o Minecraft usa a edição Bedrock. A forma mais simples é sincronizar sua skin pela conta Microsoft — sem precisar de USB.',
        steps: [
          { title: 'Baixe sua skin no celular ou PC', desc: 'Crie sua skin no MakeSkins pelo celular ou PC e baixe o arquivo .png.' },
          { title: 'Acesse minecraft.net', desc: 'Abra um navegador no celular ou PC e acesse minecraft.net. Entre com a mesma conta Microsoft que usa no Xbox.' },
          { title: 'Vá ao seu perfil', desc: 'Clique no seu nome no canto superior direito → "Meu perfil" → "Alterar aparência".' },
          { title: 'Faça upload da skin', desc: 'Selecione "Enviar skin" → escolha o arquivo .png baixado do MakeSkins → escolha modelo Steve ou Alex.' },
          { title: 'Salve as alterações', desc: 'Clique em "Salvar". A skin fica vinculada à sua conta Microsoft.' },
          { title: 'Abra o Minecraft no Xbox', desc: 'Ligue seu Xbox e abra o Minecraft. A skin sincroniza automaticamente ao fazer login. Pronto!' },
        ],
        tip: 'Esta sincronização funciona para todos os seus dispositivos Bedrock de uma vez: Xbox, celular, Switch e Windows. Uma mudança atualiza sua skin em todo lugar.',
        tipLabel: '💡 Dica',
        ctaTitle: 'Ainda não tem sua skin?',
        ctaBtn: 'Criar minha skin grátis →',
      },
    },
  },
  {
    slug: 'playstation',
    icon: '🕹️',
    platformName: { es: 'PlayStation', en: 'PlayStation', fr: 'PlayStation', pt: 'PlayStation' },
    content: {
      es: {
        metaTitle: 'Cómo poner una skin personalizada en Minecraft para PS4 y PS5 – MakeSkins',
        metaDesc: 'Tutorial para instalar tu propia skin en Minecraft para PlayStation 4 y PlayStation 5. Sin complicaciones.',
        title: 'Cómo instalar tu skin en Minecraft para PlayStation (PS4/PS5)',
        intro: 'Minecraft en PlayStation usa la edición Bedrock. Puedes instalar tu skin desde minecraft.net o directamente en la consola.',
        steps: [
          { title: 'Descarga tu skin', desc: 'Crea tu skin en MakeSkins desde tu móvil u ordenador y descarga el archivo .png.' },
          { title: 'Abre minecraft.net en tu móvil u ordenador', desc: 'Ve a minecraft.net e inicia sesión con tu cuenta de Microsoft (necesitas una cuenta gratuita de Microsoft vinculada a tu PlayStation).' },
          { title: 'Ve a tu perfil → Cambiar apariencia', desc: 'Haz clic en tu nombre → "Mi perfil" → "Cambiar apariencia" → "Subir skin".' },
          { title: 'Sube el archivo .png', desc: 'Selecciona el archivo .png descargado de MakeSkins. Elige el modelo Steve o Alex.' },
          { title: 'Guarda y entra al juego', desc: 'Pulsa "Guardar". Abre Minecraft en tu PlayStation — la skin se sincronizará automáticamente con tu cuenta.' },
          { title: 'Alternativa: desde la consola', desc: 'En el juego: Ajustes → Perfil → Editar personaje → Skins clásicas → Elegir archivo desde USB.' },
        ],
        tip: 'Necesitas vincular una cuenta de Microsoft gratuita a tu cuenta de PlayStation para usar skins personalizadas. Es un proceso rápido que solo haces una vez.',
        tipLabel: '💡 Importante',
        ctaTitle: '¿Aún no tienes tu skin?',
        ctaBtn: 'Crear mi skin gratis →',
      },
      en: {
        metaTitle: 'How to set a custom skin in Minecraft for PS4 and PS5 – MakeSkins',
        metaDesc: 'Tutorial to install your own skin in Minecraft for PlayStation 4 and PlayStation 5.',
        title: 'How to install your skin in Minecraft for PlayStation (PS4/PS5)',
        intro: 'Minecraft on PlayStation uses the Bedrock edition. You can install your skin from minecraft.net or directly on the console.',
        steps: [
          { title: 'Download your skin', desc: 'Create your skin on MakeSkins from your phone or PC and download the .png file.' },
          { title: 'Open minecraft.net on phone or PC', desc: 'Go to minecraft.net and sign in with your Microsoft account (you need a free Microsoft account linked to your PlayStation).' },
          { title: 'Go to your profile → Change Appearance', desc: 'Click your name → "My Profile" → "Change Appearance" → "Upload skin".' },
          { title: 'Upload the .png file', desc: 'Select the .png file downloaded from MakeSkins. Choose the Steve or Alex model.' },
          { title: 'Save and launch the game', desc: 'Click "Save". Open Minecraft on your PlayStation — the skin will sync automatically with your account.' },
          { title: 'Alternative: from the console', desc: 'In-game: Settings → Profile → Edit Character → Classic Skins → Choose file from USB.' },
        ],
        tip: 'You need to link a free Microsoft account to your PlayStation account to use custom skins. It\'s a quick one-time process.',
        tipLabel: '💡 Important',
        ctaTitle: "Don't have your skin yet?",
        ctaBtn: 'Create my skin for free →',
      },
      fr: {
        metaTitle: 'Comment mettre un skin personnalisé sur Minecraft PS4 et PS5 – MakeSkins',
        metaDesc: 'Tutoriel pour installer ton propre skin sur Minecraft pour PlayStation 4 et PlayStation 5.',
        title: 'Comment installer ton skin sur Minecraft pour PlayStation (PS4/PS5)',
        intro: "Minecraft sur PlayStation utilise l'édition Bedrock. Tu peux installer ton skin depuis minecraft.net ou directement sur la console.",
        steps: [
          { title: 'Télécharge ton skin', desc: 'Crée ton skin sur MakeSkins depuis ton téléphone ou PC et télécharge le fichier .png.' },
          { title: 'Ouvre minecraft.net sur téléphone ou PC', desc: 'Va sur minecraft.net et connecte-toi avec ton compte Microsoft (tu as besoin d\'un compte Microsoft gratuit lié à ton PlayStation).' },
          { title: 'Profil → Changer d\'apparence', desc: 'Clique sur ton nom → "Mon profil" → "Changer d\'apparence" → "Importer un skin".' },
          { title: 'Importe le fichier .png', desc: 'Sélectionne le fichier .png téléchargé depuis MakeSkins. Choisis le modèle Steve ou Alex.' },
          { title: 'Sauvegarde et lance le jeu', desc: 'Clique sur "Sauvegarder". Lance Minecraft sur ta PlayStation — le skin se synchronisera automatiquement.' },
          { title: 'Alternative : depuis la console', desc: 'Dans le jeu : Paramètres → Profil → Modifier le personnage → Skins classiques → Choisir depuis USB.' },
        ],
        tip: "Tu dois lier un compte Microsoft gratuit à ton compte PlayStation pour utiliser des skins personnalisés. C'est rapide et se fait une seule fois.",
        tipLabel: '💡 Important',
        ctaTitle: 'Tu n\'as pas encore ton skin ?',
        ctaBtn: 'Créer mon skin gratuitement →',
      },
      pt: {
        metaTitle: 'Como colocar uma skin personalizada no Minecraft PS4 e PS5 – MakeSkins',
        metaDesc: 'Tutorial para instalar sua própria skin no Minecraft para PlayStation 4 e PlayStation 5.',
        title: 'Como instalar sua skin no Minecraft para PlayStation (PS4/PS5)',
        intro: 'O Minecraft no PlayStation usa a edição Bedrock. Você pode instalar sua skin pelo minecraft.net ou diretamente no console.',
        steps: [
          { title: 'Baixe sua skin', desc: 'Crie sua skin no MakeSkins pelo celular ou PC e baixe o arquivo .png.' },
          { title: 'Acesse minecraft.net no celular ou PC', desc: 'Vá para minecraft.net e entre com sua conta Microsoft (você precisa de uma conta gratuita vinculada ao PlayStation).' },
          { title: 'Perfil → Alterar aparência', desc: 'Clique no seu nome → "Meu perfil" → "Alterar aparência" → "Enviar skin".' },
          { title: 'Faça upload do arquivo .png', desc: 'Selecione o arquivo .png baixado do MakeSkins. Escolha o modelo Steve ou Alex.' },
          { title: 'Salve e abra o jogo', desc: 'Clique em "Salvar". Abra o Minecraft no seu PlayStation — a skin vai sincronizar automaticamente.' },
          { title: 'Alternativa: do console', desc: 'No jogo: Configurações → Perfil → Editar personagem → Skins Clássicas → Escolher arquivo por USB.' },
        ],
        tip: 'Você precisa vincular uma conta Microsoft gratuita à sua conta PlayStation para usar skins personalizadas. É rápido e só precisa ser feito uma vez.',
        tipLabel: '💡 Importante',
        ctaTitle: 'Ainda não tem sua skin?',
        ctaBtn: 'Criar minha skin grátis →',
      },
    },
  },
  {
    slug: 'switch',
    icon: '🔴',
    platformName: { es: 'Nintendo Switch', en: 'Nintendo Switch', fr: 'Nintendo Switch', pt: 'Nintendo Switch' },
    content: {
      es: {
        metaTitle: 'Cómo poner una skin personalizada en Minecraft para Nintendo Switch – MakeSkins',
        metaDesc: 'Guía para instalar tu propia skin en Minecraft para Nintendo Switch usando tu cuenta de Microsoft.',
        title: 'Cómo instalar tu skin en Minecraft para Nintendo Switch',
        intro: 'Minecraft en Nintendo Switch es la edición Bedrock. La forma más fácil de usar una skin personalizada es sincronizarla desde minecraft.net con tu cuenta Microsoft.',
        steps: [
          { title: 'Descarga tu skin en el móvil u ordenador', desc: 'Crea tu skin en MakeSkins y descarga el archivo .png en tu teléfono o PC.' },
          { title: 'Ve a minecraft.net', desc: 'Abre un navegador en tu móvil u ordenador. Ve a minecraft.net e inicia sesión con tu cuenta de Microsoft.' },
          { title: 'Accede a tu perfil', desc: 'Haz clic en tu nombre → "Mi perfil" → "Cambiar apariencia".' },
          { title: 'Sube tu skin', desc: 'Haz clic en "Subir skin" → selecciona el archivo .png de MakeSkins → elige modelo Steve o Alex → guarda.' },
          { title: 'Abre Minecraft en Switch', desc: 'Enciende tu Nintendo Switch y abre Minecraft. Asegúrate de estar conectado con tu cuenta de Microsoft.' },
          { title: 'Sincroniza', desc: 'La skin se sincronizará automáticamente al iniciar el juego. Si no aparece, ve a Ajustes → Perfil → Editar personaje.' },
        ],
        tip: 'Necesitas una cuenta de Microsoft gratuita vinculada a tu Nintendo Switch para sincronizar skins. Si ya juegas en servidores de Minecraft en Switch, probablemente ya la tienes.',
        tipLabel: '💡 Requisito',
        ctaTitle: '¿Aún no tienes tu skin?',
        ctaBtn: 'Crear mi skin gratis →',
      },
      en: {
        metaTitle: 'How to set a custom skin in Minecraft for Nintendo Switch – MakeSkins',
        metaDesc: 'Guide to install your own skin in Minecraft for Nintendo Switch using your Microsoft account.',
        title: 'How to install your skin in Minecraft for Nintendo Switch',
        intro: 'Minecraft on Nintendo Switch is the Bedrock edition. The easiest way to use a custom skin is to sync it from minecraft.net with your Microsoft account.',
        steps: [
          { title: 'Download your skin on phone or PC', desc: 'Create your skin on MakeSkins and download the .png file to your phone or PC.' },
          { title: 'Go to minecraft.net', desc: 'Open a browser on your phone or PC. Go to minecraft.net and sign in with your Microsoft account.' },
          { title: 'Access your profile', desc: 'Click your name → "My Profile" → "Change Appearance".' },
          { title: 'Upload your skin', desc: 'Click "Upload skin" → select the .png file from MakeSkins → choose Steve or Alex model → save.' },
          { title: 'Open Minecraft on Switch', desc: 'Turn on your Nintendo Switch and open Minecraft. Make sure you are signed in with your Microsoft account.' },
          { title: 'Sync', desc: 'The skin will sync automatically when you launch the game. If it doesn\'t appear, go to Settings → Profile → Edit Character.' },
        ],
        tip: 'You need a free Microsoft account linked to your Nintendo Switch to sync skins. If you already play on Minecraft servers on Switch, you probably already have one.',
        tipLabel: '💡 Requirement',
        ctaTitle: "Don't have your skin yet?",
        ctaBtn: 'Create my skin for free →',
      },
      fr: {
        metaTitle: 'Comment mettre un skin personnalisé sur Minecraft pour Nintendo Switch – MakeSkins',
        metaDesc: 'Guide pour installer ton propre skin sur Minecraft pour Nintendo Switch avec ton compte Microsoft.',
        title: 'Comment installer ton skin sur Minecraft pour Nintendo Switch',
        intro: "Minecraft sur Nintendo Switch est l'édition Bedrock. La façon la plus simple est de synchroniser ton skin depuis minecraft.net avec ton compte Microsoft.",
        steps: [
          { title: 'Télécharge ton skin sur téléphone ou PC', desc: 'Crée ton skin sur MakeSkins et télécharge le fichier .png sur ton téléphone ou PC.' },
          { title: 'Va sur minecraft.net', desc: 'Ouvre un navigateur sur ton téléphone ou PC. Va sur minecraft.net et connecte-toi avec ton compte Microsoft.' },
          { title: 'Accède à ton profil', desc: 'Clique sur ton nom → "Mon profil" → "Changer d\'apparence".' },
          { title: 'Importe ton skin', desc: 'Clique sur "Importer un skin" → sélectionne le fichier .png de MakeSkins → choisis Steve ou Alex → sauvegarde.' },
          { title: 'Ouvre Minecraft sur Switch', desc: 'Allume ta Nintendo Switch et lance Minecraft. Assure-toi d\'être connecté avec ton compte Microsoft.' },
          { title: 'Synchronise', desc: 'Le skin se synchronisera automatiquement au lancement du jeu. Sinon, va dans Paramètres → Profil → Modifier le personnage.' },
        ],
        tip: "Tu as besoin d'un compte Microsoft gratuit lié à ta Nintendo Switch pour synchroniser les skins.",
        tipLabel: '💡 Prérequis',
        ctaTitle: 'Tu n\'as pas encore ton skin ?',
        ctaBtn: 'Créer mon skin gratuitement →',
      },
      pt: {
        metaTitle: 'Como colocar uma skin personalizada no Minecraft para Nintendo Switch – MakeSkins',
        metaDesc: 'Guia para instalar sua própria skin no Minecraft para Nintendo Switch usando sua conta Microsoft.',
        title: 'Como instalar sua skin no Minecraft para Nintendo Switch',
        intro: 'O Minecraft no Nintendo Switch é a edição Bedrock. A forma mais fácil é sincronizar sua skin pelo minecraft.net com sua conta Microsoft.',
        steps: [
          { title: 'Baixe sua skin no celular ou PC', desc: 'Crie sua skin no MakeSkins e baixe o arquivo .png no celular ou PC.' },
          { title: 'Acesse minecraft.net', desc: 'Abra um navegador no celular ou PC. Vá para minecraft.net e entre com sua conta Microsoft.' },
          { title: 'Acesse seu perfil', desc: 'Clique no seu nome → "Meu perfil" → "Alterar aparência".' },
          { title: 'Faça upload da skin', desc: 'Clique em "Enviar skin" → selecione o arquivo .png do MakeSkins → escolha Steve ou Alex → salve.' },
          { title: 'Abra o Minecraft no Switch', desc: 'Ligue seu Nintendo Switch e abra o Minecraft. Certifique-se de estar logado com sua conta Microsoft.' },
          { title: 'Sincronize', desc: 'A skin sincronizará automaticamente ao iniciar o jogo. Se não aparecer, vá em Configurações → Perfil → Editar personagem.' },
        ],
        tip: 'Você precisa de uma conta Microsoft gratuita vinculada ao seu Nintendo Switch para sincronizar skins.',
        tipLabel: '💡 Requisito',
        ctaTitle: 'Ainda não tem sua skin?',
        ctaBtn: 'Criar minha skin grátis →',
      },
    },
  },
  {
    slug: 'movil',
    icon: '📱',
    platformName: { es: 'Móvil (iOS / Android)', en: 'Mobile (iOS / Android)', fr: 'Mobile (iOS / Android)', pt: 'Mobile (iOS / Android)' },
    content: {
      es: {
        metaTitle: 'Cómo poner una skin personalizada en Minecraft para móvil (iPhone y Android) – MakeSkins',
        metaDesc: 'Guía para instalar tu propia skin en Minecraft Pocket Edition (iOS y Android) en pocos pasos.',
        title: 'Cómo instalar tu skin en Minecraft para móvil (iOS/Android)',
        intro: 'Minecraft en móvil (también llamado Minecraft Pocket Edition o MCPE) es la edición Bedrock. Puedes instalar tu skin directamente desde el juego en tu teléfono.',
        steps: [
          { title: 'Crea y descarga tu skin', desc: 'Desde tu mismo móvil, crea tu skin en MakeSkins y descarga el archivo .png. Guárdalo en la galería o en Archivos.' },
          { title: 'Abre Minecraft', desc: 'Inicia Minecraft en tu iPhone o Android. Ve al menú principal.' },
          { title: 'Toca tu perfil', desc: 'Toca el icono de tu personaje (esquina superior izquierda) o ve a "Ajustes" → "Perfil".' },
          { title: 'Editar personaje → Skins clásicas', desc: 'Toca "Editar personaje" → busca la pestaña "Skins clásicas" (no el creador de personaje habitual).' },
          { title: 'Elige tu skin', desc: 'Toca "Elegir nuevo skin" → "Elegir archivos" → navega hasta el .png descargado → selecciónalo.' },
          { title: 'Confirma el modelo', desc: 'Elige entre Steve (brazos anchos) o Alex (brazos delgados). Toca "Confirmar". ¡Ya está!' },
        ],
        tip: 'Todo el proceso se hace directamente desde tu móvil sin necesidad de ordenador. MakeSkins funciona perfectamente en el navegador del móvil.',
        tipLabel: '💡 Sin ordenador',
        ctaTitle: '¿Aún no tienes tu skin?',
        ctaBtn: 'Crear mi skin gratis →',
      },
      en: {
        metaTitle: 'How to install a custom skin in Minecraft Mobile (iPhone & Android) – MakeSkins',
        metaDesc: 'Guide to install your own skin in Minecraft Pocket Edition (iOS and Android) in just a few steps.',
        title: 'How to install your skin in Minecraft Mobile (iOS/Android)',
        intro: 'Minecraft on mobile (also known as Minecraft Pocket Edition or MCPE) is the Bedrock edition. You can install your skin directly from the game on your phone.',
        steps: [
          { title: 'Create and download your skin', desc: 'From your phone, create your skin on MakeSkins and download the .png file. Save it to your gallery or Files app.' },
          { title: 'Open Minecraft', desc: 'Launch Minecraft on your iPhone or Android. Go to the main menu.' },
          { title: 'Tap your profile', desc: 'Tap the character icon (top-left corner) or go to "Settings" → "Profile".' },
          { title: 'Edit Character → Classic Skins', desc: 'Tap "Edit Character" → look for the "Classic Skins" tab (not the regular character creator).' },
          { title: 'Choose your skin', desc: 'Tap "Choose new skin" → "Choose files" → navigate to the downloaded .png → select it.' },
          { title: 'Confirm the model', desc: 'Choose between Steve (wide arms) or Alex (slim arms). Tap "Confirm". Done!' },
        ],
        tip: 'The whole process can be done on your phone without a computer. MakeSkins works perfectly in the mobile browser.',
        tipLabel: '💡 No computer needed',
        ctaTitle: "Don't have your skin yet?",
        ctaBtn: 'Create my skin for free →',
      },
      fr: {
        metaTitle: 'Comment installer un skin personnalisé sur Minecraft Mobile (iPhone et Android) – MakeSkins',
        metaDesc: 'Guide pour installer ton propre skin sur Minecraft Pocket Edition (iOS et Android) en quelques étapes.',
        title: 'Comment installer ton skin sur Minecraft Mobile (iOS/Android)',
        intro: "Minecraft sur mobile (aussi appelé Minecraft Pocket Edition ou MCPE) est l'édition Bedrock. Tu peux installer ton skin directement depuis le jeu.",
        steps: [
          { title: 'Crée et télécharge ton skin', desc: 'Depuis ton téléphone, crée ton skin sur MakeSkins et télécharge le fichier .png. Sauvegarde-le dans ta galerie.' },
          { title: 'Ouvre Minecraft', desc: 'Lance Minecraft sur ton iPhone ou Android.' },
          { title: 'Touche ton profil', desc: 'Touche l\'icône de ton personnage (coin supérieur gauche) ou va dans "Paramètres" → "Profil".' },
          { title: 'Modifier le personnage → Skins classiques', desc: 'Touche "Modifier le personnage" → cherche l\'onglet "Skins classiques".' },
          { title: 'Choisis ton skin', desc: 'Touche "Choisir un nouveau skin" → "Choisir les fichiers" → navigue jusqu\'au .png téléchargé → sélectionne-le.' },
          { title: 'Confirme le modèle', desc: 'Choisis entre Steve (bras larges) ou Alex (bras fins). Touche "Confirmer". C\'est fait !' },
        ],
        tip: "Tout le processus se fait directement sur ton téléphone, sans ordinateur. MakeSkins fonctionne parfaitement dans le navigateur mobile.",
        tipLabel: '💡 Sans ordinateur',
        ctaTitle: 'Tu n\'as pas encore ton skin ?',
        ctaBtn: 'Créer mon skin gratuitement →',
      },
      pt: {
        metaTitle: 'Como instalar uma skin no Minecraft Mobile (iPhone e Android) – MakeSkins',
        metaDesc: 'Guia para instalar sua própria skin no Minecraft Pocket Edition (iOS e Android) em poucos passos.',
        title: 'Como instalar sua skin no Minecraft Mobile (iOS/Android)',
        intro: 'O Minecraft no celular (também chamado de Minecraft Pocket Edition ou MCPE) é a edição Bedrock. Você pode instalar sua skin diretamente do jogo.',
        steps: [
          { title: 'Crie e baixe sua skin', desc: 'No seu celular, crie sua skin no MakeSkins e baixe o arquivo .png. Salve na galeria ou no app Arquivos.' },
          { title: 'Abra o Minecraft', desc: 'Inicie o Minecraft no seu iPhone ou Android. Vá ao menu principal.' },
          { title: 'Toque no seu perfil', desc: 'Toque no ícone do personagem (canto superior esquerdo) ou vá em "Configurações" → "Perfil".' },
          { title: 'Editar personagem → Skins Clássicas', desc: 'Toque em "Editar personagem" → procure a aba "Skins Clássicas".' },
          { title: 'Escolha sua skin', desc: 'Toque em "Escolher nova skin" → "Escolher arquivos" → navegue até o .png baixado → selecione.' },
          { title: 'Confirme o modelo', desc: 'Escolha entre Steve (braços largos) ou Alex (braços finos). Toque em "Confirmar". Pronto!' },
        ],
        tip: 'Todo o processo pode ser feito no celular sem computador. O MakeSkins funciona perfeitamente no navegador mobile.',
        tipLabel: '💡 Sem computador',
        ctaTitle: 'Ainda não tem sua skin?',
        ctaBtn: 'Criar minha skin grátis →',
      },
    },
  },
]

export const GUIDES_INDEX: Record<Locale, { title: string; subtitle: string; metaTitle: string; metaDesc: string }> = {
  es: {
    metaTitle: 'Guías: Cómo instalar skins de Minecraft en PC, Xbox, PS4, Switch y móvil – MakeSkins',
    metaDesc: 'Tutoriales paso a paso para instalar tu skin de Minecraft en todas las plataformas: Java, Bedrock, Xbox, PlayStation, Nintendo Switch e iOS/Android.',
    title: 'Cómo instalar tu skin de Minecraft',
    subtitle: 'Guías paso a paso para todas las plataformas',
  },
  en: {
    metaTitle: 'Guides: How to install Minecraft skins on PC, Xbox, PS4, Switch and mobile – MakeSkins',
    metaDesc: 'Step-by-step tutorials to install your Minecraft skin on all platforms: Java, Bedrock, Xbox, PlayStation, Nintendo Switch and iOS/Android.',
    title: 'How to install your Minecraft skin',
    subtitle: 'Step-by-step guides for all platforms',
  },
  fr: {
    metaTitle: 'Guides : Comment installer des skins Minecraft sur PC, Xbox, PS4, Switch et mobile – MakeSkins',
    metaDesc: 'Tutoriels étape par étape pour installer ton skin Minecraft sur toutes les plateformes.',
    title: 'Comment installer ton skin Minecraft',
    subtitle: 'Guides étape par étape pour toutes les plateformes',
  },
  pt: {
    metaTitle: 'Guias: Como instalar skins do Minecraft no PC, Xbox, PS4, Switch e celular – MakeSkins',
    metaDesc: 'Tutoriais passo a passo para instalar sua skin do Minecraft em todas as plataformas.',
    title: 'Como instalar sua skin do Minecraft',
    subtitle: 'Guias passo a passo para todas as plataformas',
  },
}
